
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'FooterNav': typeof import("../../app/components/FooterNav.vue")['default']
  'CatalogProductAddAttributeSet': typeof import("../../app/components/catalog/product/add-attribute-set.vue")['default']
  'CatalogProductAddAttribute': typeof import("../../app/components/catalog/product/add-attribute.vue")['default']
  'CatalogProductAddProduct': typeof import("../../app/components/catalog/product/add-product.vue")['default']
  'CatalogProductAddShowcase': typeof import("../../app/components/catalog/product/add-showcase.vue")['default']
  'CatalogProductAddStation': typeof import("../../app/components/catalog/product/add-station.vue")['default']
  'CatalogProductBestsellers': typeof import("../../app/components/catalog/product/bestsellers.vue")['default']
  'CatalogProductBrands': typeof import("../../app/components/catalog/product/brands.vue")['default']
  'CatalogProductColorOptions': typeof import("../../app/components/catalog/product/colorOptions.vue")['default']
  'CatalogProductDeals': typeof import("../../app/components/catalog/product/deals.vue")['default']
  'CatalogProductExclusives': typeof import("../../app/components/catalog/product/exclusives.vue")['default']
  'CatalogProductFeaturedproducts': typeof import("../../app/components/catalog/product/featuredproducts.vue")['default']
  'CatalogProductGiftCard': typeof import("../../app/components/catalog/product/giftCard.vue")['default']
  'CatalogProductLatestproducts': typeof import("../../app/components/catalog/product/latestproducts.vue")['default']
  'CatalogProductCard': typeof import("../../app/components/catalog/product/productCard.vue")['default']
  'CatalogProductCompare': typeof import("../../app/components/catalog/product/productCompare.vue")['default']
  'CatalogProductCompareTable': typeof import("../../app/components/catalog/product/productCompareTable.vue")['default']
  'CatalogProductDetails': typeof import("../../app/components/catalog/product/productDetails.vue")['default']
  'CatalogProductFaqs': typeof import("../../app/components/catalog/product/productFaqs.vue")['default']
  'CatalogProductGallery': typeof import("../../app/components/catalog/product/productGallery.vue")['default']
  'CatalogProductQty': typeof import("../../app/components/catalog/product/productQty.vue")['default']
  'CatalogProductReviews': typeof import("../../app/components/catalog/product/productReviews.vue")['default']
  'CatalogProductSpecs': typeof import("../../app/components/catalog/product/productSpecs.vue")['default']
  'CatalogProductRadiostation': typeof import("../../app/components/catalog/product/radiostation.vue")['default']
  'CatalogProductRecentlyviewed': typeof import("../../app/components/catalog/product/recentlyviewed.vue")['default']
  'CatalogProductRelatedproducts': typeof import("../../app/components/catalog/product/relatedproducts.vue")['default']
  'CatalogProductRelatedstations': typeof import("../../app/components/catalog/product/relatedstations.vue")['default']
  'CatalogProductShippingOptions': typeof import("../../app/components/catalog/product/shippingOptions.vue")['default']
  'CatalogProductSizeOptions': typeof import("../../app/components/catalog/product/sizeOptions.vue")['default']
  'CatalogProductUpdateAttributeSet': typeof import("../../app/components/catalog/product/update-attribute-set.vue")['default']
  'CatalogProductUpdateAttribute': typeof import("../../app/components/catalog/product/update-attribute.vue")['default']
  'CatalogProductUpdateProduct': typeof import("../../app/components/catalog/product/update-product.vue")['default']
  'CatalogProductUpdateShowcase': typeof import("../../app/components/catalog/product/update-showcase.vue")['default']
  'CatalogShopsRelatedstores': typeof import("../../app/components/catalog/shops/relatedstores.vue")['default']
  'CatalogShopsRestaurant': typeof import("../../app/components/catalog/shops/restaurant.vue")['default']
  'CatalogShopsStores': typeof import("../../app/components/catalog/shops/stores.vue")['default']
  'CatalogVendorBlocksBiggestcustomers': typeof import("../../app/components/catalog/vendor/blocks/biggestcustomers.vue")['default']
  'CatalogVendorBlocksLowestselling': typeof import("../../app/components/catalog/vendor/blocks/lowestselling.vue")['default']
  'CatalogVendorBlocksTopcategories': typeof import("../../app/components/catalog/vendor/blocks/topcategories.vue")['default']
  'CatalogVendorBlocksTopproducts': typeof import("../../app/components/catalog/vendor/blocks/topproducts.vue")['default']
  'CatalogVendorPagesAttributes': typeof import("../../app/components/catalog/vendor/pages/attributes.vue")['default']
  'CatalogVendorPagesCommissions': typeof import("../../app/components/catalog/vendor/pages/commissions.vue")['default']
  'CatalogVendorPagesCrm': typeof import("../../app/components/catalog/vendor/pages/crm.vue")['default']
  'CatalogVendorPagesDashboard': typeof import("../../app/components/catalog/vendor/pages/dashboard.vue")['default']
  'CatalogVendorPagesEmails': typeof import("../../app/components/catalog/vendor/pages/emails.vue")['default']
  'CatalogVendorPagesEnquiries': typeof import("../../app/components/catalog/vendor/pages/enquiries.vue")['default']
  'CatalogVendorPagesInvoices': typeof import("../../app/components/catalog/vendor/pages/invoices.vue")['default']
  'CatalogVendorPagesOrders': typeof import("../../app/components/catalog/vendor/pages/orders.vue")['default']
  'CatalogVendorPagesProducts': typeof import("../../app/components/catalog/vendor/pages/products.vue")['default']
  'CatalogVendorPagesReviews': typeof import("../../app/components/catalog/vendor/pages/reviews.vue")['default']
  'CatalogVendorPagesShipments': typeof import("../../app/components/catalog/vendor/pages/shipments.vue")['default']
  'CatalogVendorPagesStores': typeof import("../../app/components/catalog/vendor/pages/stores.vue")['default']
  'ContentBlocksBreadcrumbs': typeof import("../../app/components/content/blocks/breadcrumbs.vue")['default']
  'ContentBlocksCurrencySwitcher': typeof import("../../app/components/content/blocks/currencySwitcher.vue")['default']
  'ContentBlocksLanguageSwitcher': typeof import("../../app/components/content/blocks/languageSwitcher.vue")['default']
  'ContentBlocksVideoproduct': typeof import("../../app/components/content/blocks/videoproduct.vue")['default']
  'Ecosystemmenu': typeof import("../../app/components/ecosystemmenu.vue")['default']
  'MarketingAddCoupon': typeof import("../../app/components/marketing/add-coupon.vue")['default']
  'MarketingAddRewards': typeof import("../../app/components/marketing/add-rewards.vue")['default']
  'MarketingCoupons': typeof import("../../app/components/marketing/coupons.vue")['default']
  'MarketingPromotionsCoupons': typeof import("../../app/components/marketing/promotions/coupons.vue")['default']
  'MarketingPromotionsGiftcard[id]': typeof import("../../app/components/marketing/promotions/giftcard/[id].vue")['default']
  'MarketingPromotionsGiftcardReload': typeof import("../../app/components/marketing/promotions/giftcard/reload.vue")['default']
  'MarketingPromotionsGiftcards': typeof import("../../app/components/marketing/promotions/giftcards.vue")['default']
  'MarketingPromotionsSubscription[id]': typeof import("../../app/components/marketing/promotions/subscription/[id].vue")['default']
  'MarketingPromotionsSubscriptions': typeof import("../../app/components/marketing/promotions/subscriptions.vue")['default']
  'MarketingUpdateRewards': typeof import("../../app/components/marketing/update-rewards.vue")['default']
  'MenusLowernav': typeof import("../../app/components/menus/lowernav.vue")['default']
  'PartialsLocaleSelector': typeof import("../../app/components/partials/LocaleSelector.vue")['default']
  'PartialsStripePayment': typeof import("../../app/components/partials/StripePayment.vue")['default']
  'PartialsAddToCartBtn': typeof import("../../app/components/partials/addToCartBtn.vue")['default']
  'PartialsCartItem': typeof import("../../app/components/partials/cartItem.vue")['default']
  'PartialsCheckoutButton': typeof import("../../app/components/partials/checkoutButton.vue")['default']
  'PartialsCompareBtn': typeof import("../../app/components/partials/compareBtn.vue")['default']
  'PartialsRatings': typeof import("../../app/components/partials/ratings.vue")['default']
  'PartialsStoreCurrencySelector': typeof import("../../app/components/partials/store/CurrencySelector.vue")['default']
  'PartialsStoreSwitcher': typeof import("../../app/components/partials/store/StoreSwitcher.vue")['default']
  'RelatedRelatedposts': typeof import("../../app/components/related/relatedposts.vue")['default']
  'RelatedRelatedproducts': typeof import("../../app/components/related/relatedproducts.vue")['default']
  'SalesOrderDetailsDialog': typeof import("../../app/components/sales/OrderDetailsDialog.vue")['default']
  'SalesOrderManagement': typeof import("../../app/components/sales/OrderManagement.vue")['default']
  'SalesReceiptsTab': typeof import("../../app/components/sales/ReceiptsTab.vue")['default']
  'SalesReturnRequestDialog': typeof import("../../app/components/sales/ReturnRequestDialog.vue")['default']
  'SalesReturnsTab': typeof import("../../app/components/sales/ReturnsTab.vue")['default']
  'SalesTransactionsTab': typeof import("../../app/components/sales/TransactionsTab.vue")['default']
  'SalesBrandsRelatedbrands': typeof import("../../app/components/sales/brands/relatedbrands.vue")['default']
  'SalesCreditMemos': typeof import("../../app/components/sales/creditMemos.vue")['default']
  'SalesInvoices': typeof import("../../app/components/sales/invoices.vue")['default']
  'SalesOrdersAgreements': typeof import("../../app/components/sales/orders/agreements.vue")['default']
  'SalesOrdersCreditmemo[id]': typeof import("../../app/components/sales/orders/creditmemo/[id].vue")['default']
  'SalesOrdersCreditmemos': typeof import("../../app/components/sales/orders/creditmemos.vue")['default']
  'SalesOrdersInvoice[id]': typeof import("../../app/components/sales/orders/invoice/[id].vue")['default']
  'SalesOrdersInvoices': typeof import("../../app/components/sales/orders/invoices.vue")['default']
  'SalesOrdersMyOrder[id]': typeof import("../../app/components/sales/orders/my-order/[id].vue")['default']
  'SalesOrdersMyOrders': typeof import("../../app/components/sales/orders/my-orders.vue")['default']
  'SalesOrdersPayments': typeof import("../../app/components/sales/orders/payments.vue")['default']
  'SalesOrdersReturn': typeof import("../../app/components/sales/orders/return.vue")['default']
  'SalesOrdersReturns': typeof import("../../app/components/sales/orders/returns.vue")['default']
  'SalesOrdersShipment[id]': typeof import("../../app/components/sales/orders/shipment/[id].vue")['default']
  'SalesOrdersShipments': typeof import("../../app/components/sales/orders/shipments.vue")['default']
  'SalesOrdersTransaction[id]': typeof import("../../app/components/sales/orders/transaction/[id].vue")['default']
  'SalesOrdersTransactions': typeof import("../../app/components/sales/orders/transactions.vue")['default']
  'SalesOrdersTab': typeof import("../../app/components/sales/ordersTab.vue")['default']
  'SalesPaymentsPriceDisplay': typeof import("../../app/components/sales/payments/PriceDisplay.vue")['default']
  'SalesPaymentsStripePaymentElement': typeof import("../../app/components/sales/payments/StripePaymentElement.vue")['default']
  'Search': typeof import("../../app/components/search/search.vue")['default']
  'ShopCartItem': typeof import("../../app/components/shop/cart/cartItem.vue")['default']
  'ShopCartCheckout': typeof import("../../app/components/shop/cart/checkout.vue")['default']
  'ShopCheckoutStripeCardElement': typeof import("../../app/components/shop/checkout/StripeCardElement.vue")['default']
  'ShopCheckoutStripeCheckout': typeof import("../../app/components/shop/checkout/StripeCheckout.vue")['default']
  'ShopCheckoutAddressBilling': typeof import("../../app/components/shop/checkout/addressBilling.vue")['default']
  'ShopCheckoutAddressShipping': typeof import("../../app/components/shop/checkout/addressShipping.vue")['default']
  'ShopCheckoutCartProductItem': typeof import("../../app/components/shop/checkout/cart/ProductItem.vue")['default']
  'ShopCheckoutCartPromotionItem': typeof import("../../app/components/shop/checkout/cart/PromotionItem.vue")['default']
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  'NuxtImg': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
  'NuxtPicture': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
  'SfAccordionItem': typeof import("@storefront-ui/vue")['SfAccordionItem']
  'SfBadge': typeof import("@storefront-ui/vue")['SfBadge']
  'SfButton': typeof import("@storefront-ui/vue")['SfButton']
  'SfCheckbox': typeof import("@storefront-ui/vue")['SfCheckbox']
  'SfChip': typeof import("@storefront-ui/vue")['SfChip']
  'SfCounter': typeof import("@storefront-ui/vue")['SfCounter']
  'SfDrawer': typeof import("@storefront-ui/vue")['SfDrawer']
  'SfDropdown': typeof import("@storefront-ui/vue")['SfDropdown']
  'SfIconAdd': typeof import("@storefront-ui/vue")['SfIconAdd']
  'SfIconAddShoppingCart': typeof import("@storefront-ui/vue")['SfIconAddShoppingCart']
  'SfIconAlokai': typeof import("@storefront-ui/vue")['SfIconAlokai']
  'SfIconAlokaiFull': typeof import("@storefront-ui/vue")['SfIconAlokaiFull']
  'SfIconArrowBack': typeof import("@storefront-ui/vue")['SfIconArrowBack']
  'SfIconArrowDownward': typeof import("@storefront-ui/vue")['SfIconArrowDownward']
  'SfIconArrowForward': typeof import("@storefront-ui/vue")['SfIconArrowForward']
  'SfIconArrowUpward': typeof import("@storefront-ui/vue")['SfIconArrowUpward']
  'SfIconBase': typeof import("@storefront-ui/vue")['SfIconBase']
  'SfIconBlock': typeof import("@storefront-ui/vue")['SfIconBlock']
  'SfIconCalendarToday': typeof import("@storefront-ui/vue")['SfIconCalendarToday']
  'SfIconCall': typeof import("@storefront-ui/vue")['SfIconCall']
  'SfIconCancel': typeof import("@storefront-ui/vue")['SfIconCancel']
  'SfIconCheck': typeof import("@storefront-ui/vue")['SfIconCheck']
  'SfIconCheckBox': typeof import("@storefront-ui/vue")['SfIconCheckBox']
  'SfIconCheckBoxOutlineBlank': typeof import("@storefront-ui/vue")['SfIconCheckBoxOutlineBlank']
  'SfIconCheckCircle': typeof import("@storefront-ui/vue")['SfIconCheckCircle']
  'SfIconChevronLeft': typeof import("@storefront-ui/vue")['SfIconChevronLeft']
  'SfIconChevronRight': typeof import("@storefront-ui/vue")['SfIconChevronRight']
  'SfIconCircle': typeof import("@storefront-ui/vue")['SfIconCircle']
  'SfIconClose': typeof import("@storefront-ui/vue")['SfIconClose']
  'SfIconCloseSm': typeof import("@storefront-ui/vue")['SfIconCloseSm']
  'SfIconCompareArrows': typeof import("@storefront-ui/vue")['SfIconCompareArrows']
  'SfIconContactSupport': typeof import("@storefront-ui/vue")['SfIconContactSupport']
  'SfIconCreditCard': typeof import("@storefront-ui/vue")['SfIconCreditCard']
  'SfIconDelete': typeof import("@storefront-ui/vue")['SfIconDelete']
  'SfIconDownload': typeof import("@storefront-ui/vue")['SfIconDownload']
  'SfIconEmail': typeof import("@storefront-ui/vue")['SfIconEmail']
  'SfIconError': typeof import("@storefront-ui/vue")['SfIconError']
  'SfIconExpandLess': typeof import("@storefront-ui/vue")['SfIconExpandLess']
  'SfIconExpandMore': typeof import("@storefront-ui/vue")['SfIconExpandMore']
  'SfIconFacebook': typeof import("@storefront-ui/vue")['SfIconFacebook']
  'SfIconFavorite': typeof import("@storefront-ui/vue")['SfIconFavorite']
  'SfIconFavoriteFilled': typeof import("@storefront-ui/vue")['SfIconFavoriteFilled']
  'SfIconGridView': typeof import("@storefront-ui/vue")['SfIconGridView']
  'SfIconHelp': typeof import("@storefront-ui/vue")['SfIconHelp']
  'SfIconHome': typeof import("@storefront-ui/vue")['SfIconHome']
  'SfIconIndeterminateCheckBox': typeof import("@storefront-ui/vue")['SfIconIndeterminateCheckBox']
  'SfIconInfo': typeof import("@storefront-ui/vue")['SfIconInfo']
  'SfIconInstagram': typeof import("@storefront-ui/vue")['SfIconInstagram']
  'SfIconLanguage': typeof import("@storefront-ui/vue")['SfIconLanguage']
  'SfIconLocalShipping': typeof import("@storefront-ui/vue")['SfIconLocalShipping']
  'SfIconLocalFireDepartment': typeof import("@storefront-ui/vue")['SfIconLocal_fire_department']
  'SfIconLocationOn': typeof import("@storefront-ui/vue")['SfIconLocationOn']
  'SfIconLocationOnFilled': typeof import("@storefront-ui/vue")['SfIconLocationOnFilled']
  'SfIconLock': typeof import("@storefront-ui/vue")['SfIconLock']
  'SfIconLockOpen': typeof import("@storefront-ui/vue")['SfIconLockOpen']
  'SfIconLogin': typeof import("@storefront-ui/vue")['SfIconLogin']
  'SfIconLogout': typeof import("@storefront-ui/vue")['SfIconLogout']
  'SfIconMenu': typeof import("@storefront-ui/vue")['SfIconMenu']
  'SfIconMoreHoriz': typeof import("@storefront-ui/vue")['SfIconMoreHoriz']
  'SfIconMoreVert': typeof import("@storefront-ui/vue")['SfIconMoreVert']
  'SfIconOpenInNew': typeof import("@storefront-ui/vue")['SfIconOpenInNew']
  'SfIconOpenSource': typeof import("@storefront-ui/vue")['SfIconOpenSource']
  'SfIconPackage': typeof import("@storefront-ui/vue")['SfIconPackage']
  'SfIconPercent': typeof import("@storefront-ui/vue")['SfIconPercent']
  'SfIconPerson': typeof import("@storefront-ui/vue")['SfIconPerson']
  'SfIconPinterest': typeof import("@storefront-ui/vue")['SfIconPinterest']
  'SfIconPublishedWithChanges': typeof import("@storefront-ui/vue")['SfIconPublishedWithChanges']
  'SfIconRadioButtonChecked': typeof import("@storefront-ui/vue")['SfIconRadioButtonChecked']
  'SfIconRadioButtonUnchecked': typeof import("@storefront-ui/vue")['SfIconRadioButtonUnchecked']
  'SfIconReact': typeof import("@storefront-ui/vue")['SfIconReact']
  'SfIconRemove': typeof import("@storefront-ui/vue")['SfIconRemove']
  'SfIconRemoveShoppingCart': typeof import("@storefront-ui/vue")['SfIconRemoveShoppingCart']
  'SfIconSafetyCheck': typeof import("@storefront-ui/vue")['SfIconSafetyCheck']
  'SfIconSchedule': typeof import("@storefront-ui/vue")['SfIconSchedule']
  'SfIconSearch': typeof import("@storefront-ui/vue")['SfIconSearch']
  'SfIconSell': typeof import("@storefront-ui/vue")['SfIconSell']
  'SfIconShare': typeof import("@storefront-ui/vue")['SfIconShare']
  'SfIconShoppingCart': typeof import("@storefront-ui/vue")['SfIconShoppingCart']
  'SfIconShoppingCartCheckout': typeof import("@storefront-ui/vue")['SfIconShoppingCartCheckout']
  'SfIconSort': typeof import("@storefront-ui/vue")['SfIconSort']
  'SfIconStar': typeof import("@storefront-ui/vue")['SfIconStar']
  'SfIconStarFilled': typeof import("@storefront-ui/vue")['SfIconStarFilled']
  'SfIconStarHalf': typeof import("@storefront-ui/vue")['SfIconStarHalf']
  'SfIconThumbDown': typeof import("@storefront-ui/vue")['SfIconThumbDown']
  'SfIconThumbUp': typeof import("@storefront-ui/vue")['SfIconThumbUp']
  'SfIconTune': typeof import("@storefront-ui/vue")['SfIconTune']
  'SfIconTwitter': typeof import("@storefront-ui/vue")['SfIconTwitter']
  'SfIconUndo': typeof import("@storefront-ui/vue")['SfIconUndo']
  'SfIconUnfoldMore': typeof import("@storefront-ui/vue")['SfIconUnfoldMore']
  'SfIconUpload': typeof import("@storefront-ui/vue")['SfIconUpload']
  'SfIconViewList': typeof import("@storefront-ui/vue")['SfIconViewList']
  'SfIconVisibility': typeof import("@storefront-ui/vue")['SfIconVisibility']
  'SfIconVisibilityOff': typeof import("@storefront-ui/vue")['SfIconVisibilityOff']
  'SfIconVsfDiamond': typeof import("@storefront-ui/vue")['SfIconVsfDiamond']
  'SfIconVuejs': typeof import("@storefront-ui/vue")['SfIconVuejs']
  'SfIconVuestorefront': typeof import("@storefront-ui/vue")['SfIconVuestorefront']
  'SfIconWarehouse': typeof import("@storefront-ui/vue")['SfIconWarehouse']
  'SfIconWarning': typeof import("@storefront-ui/vue")['SfIconWarning']
  'SfIconYoutube': typeof import("@storefront-ui/vue")['SfIconYoutube']
  'SfInput': typeof import("@storefront-ui/vue")['SfInput']
  'SfLink': typeof import("@storefront-ui/vue")['SfLink']
  'SfListItem': typeof import("@storefront-ui/vue")['SfListItem']
  'SfLoaderCircular': typeof import("@storefront-ui/vue")['SfLoaderCircular']
  'SfLoaderLinear': typeof import("@storefront-ui/vue")['SfLoaderLinear']
  'SfModal': typeof import("@storefront-ui/vue")['SfModal']
  'SfProgressCircular': typeof import("@storefront-ui/vue")['SfProgressCircular']
  'SfProgressLinear': typeof import("@storefront-ui/vue")['SfProgressLinear']
  'SfRadio': typeof import("@storefront-ui/vue")['SfRadio']
  'SfRating': typeof import("@storefront-ui/vue")['SfRating']
  'SfRatingButton': typeof import("@storefront-ui/vue")['SfRatingButton']
  'SfScrollable': typeof import("@storefront-ui/vue")['SfScrollable']
  'SfSelect': typeof import("@storefront-ui/vue")['SfSelect']
  'SfSwitch': typeof import("@storefront-ui/vue")['SfSwitch']
  'SfTextarea': typeof import("@storefront-ui/vue")['SfTextarea']
  'SfThumbnail': typeof import("@storefront-ui/vue")['SfThumbnail']
  'SfTooltip': typeof import("@storefront-ui/vue")['SfTooltip']
  'NuxtLinkLocale': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
  'SwitchLocalePathLink': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  'LazyFooterNav': LazyComponent<typeof import("../../app/components/FooterNav.vue")['default']>
  'LazyCatalogProductAddAttributeSet': LazyComponent<typeof import("../../app/components/catalog/product/add-attribute-set.vue")['default']>
  'LazyCatalogProductAddAttribute': LazyComponent<typeof import("../../app/components/catalog/product/add-attribute.vue")['default']>
  'LazyCatalogProductAddProduct': LazyComponent<typeof import("../../app/components/catalog/product/add-product.vue")['default']>
  'LazyCatalogProductAddShowcase': LazyComponent<typeof import("../../app/components/catalog/product/add-showcase.vue")['default']>
  'LazyCatalogProductAddStation': LazyComponent<typeof import("../../app/components/catalog/product/add-station.vue")['default']>
  'LazyCatalogProductBestsellers': LazyComponent<typeof import("../../app/components/catalog/product/bestsellers.vue")['default']>
  'LazyCatalogProductBrands': LazyComponent<typeof import("../../app/components/catalog/product/brands.vue")['default']>
  'LazyCatalogProductColorOptions': LazyComponent<typeof import("../../app/components/catalog/product/colorOptions.vue")['default']>
  'LazyCatalogProductDeals': LazyComponent<typeof import("../../app/components/catalog/product/deals.vue")['default']>
  'LazyCatalogProductExclusives': LazyComponent<typeof import("../../app/components/catalog/product/exclusives.vue")['default']>
  'LazyCatalogProductFeaturedproducts': LazyComponent<typeof import("../../app/components/catalog/product/featuredproducts.vue")['default']>
  'LazyCatalogProductGiftCard': LazyComponent<typeof import("../../app/components/catalog/product/giftCard.vue")['default']>
  'LazyCatalogProductLatestproducts': LazyComponent<typeof import("../../app/components/catalog/product/latestproducts.vue")['default']>
  'LazyCatalogProductCard': LazyComponent<typeof import("../../app/components/catalog/product/productCard.vue")['default']>
  'LazyCatalogProductCompare': LazyComponent<typeof import("../../app/components/catalog/product/productCompare.vue")['default']>
  'LazyCatalogProductCompareTable': LazyComponent<typeof import("../../app/components/catalog/product/productCompareTable.vue")['default']>
  'LazyCatalogProductDetails': LazyComponent<typeof import("../../app/components/catalog/product/productDetails.vue")['default']>
  'LazyCatalogProductFaqs': LazyComponent<typeof import("../../app/components/catalog/product/productFaqs.vue")['default']>
  'LazyCatalogProductGallery': LazyComponent<typeof import("../../app/components/catalog/product/productGallery.vue")['default']>
  'LazyCatalogProductQty': LazyComponent<typeof import("../../app/components/catalog/product/productQty.vue")['default']>
  'LazyCatalogProductReviews': LazyComponent<typeof import("../../app/components/catalog/product/productReviews.vue")['default']>
  'LazyCatalogProductSpecs': LazyComponent<typeof import("../../app/components/catalog/product/productSpecs.vue")['default']>
  'LazyCatalogProductRadiostation': LazyComponent<typeof import("../../app/components/catalog/product/radiostation.vue")['default']>
  'LazyCatalogProductRecentlyviewed': LazyComponent<typeof import("../../app/components/catalog/product/recentlyviewed.vue")['default']>
  'LazyCatalogProductRelatedproducts': LazyComponent<typeof import("../../app/components/catalog/product/relatedproducts.vue")['default']>
  'LazyCatalogProductRelatedstations': LazyComponent<typeof import("../../app/components/catalog/product/relatedstations.vue")['default']>
  'LazyCatalogProductShippingOptions': LazyComponent<typeof import("../../app/components/catalog/product/shippingOptions.vue")['default']>
  'LazyCatalogProductSizeOptions': LazyComponent<typeof import("../../app/components/catalog/product/sizeOptions.vue")['default']>
  'LazyCatalogProductUpdateAttributeSet': LazyComponent<typeof import("../../app/components/catalog/product/update-attribute-set.vue")['default']>
  'LazyCatalogProductUpdateAttribute': LazyComponent<typeof import("../../app/components/catalog/product/update-attribute.vue")['default']>
  'LazyCatalogProductUpdateProduct': LazyComponent<typeof import("../../app/components/catalog/product/update-product.vue")['default']>
  'LazyCatalogProductUpdateShowcase': LazyComponent<typeof import("../../app/components/catalog/product/update-showcase.vue")['default']>
  'LazyCatalogShopsRelatedstores': LazyComponent<typeof import("../../app/components/catalog/shops/relatedstores.vue")['default']>
  'LazyCatalogShopsRestaurant': LazyComponent<typeof import("../../app/components/catalog/shops/restaurant.vue")['default']>
  'LazyCatalogShopsStores': LazyComponent<typeof import("../../app/components/catalog/shops/stores.vue")['default']>
  'LazyCatalogVendorBlocksBiggestcustomers': LazyComponent<typeof import("../../app/components/catalog/vendor/blocks/biggestcustomers.vue")['default']>
  'LazyCatalogVendorBlocksLowestselling': LazyComponent<typeof import("../../app/components/catalog/vendor/blocks/lowestselling.vue")['default']>
  'LazyCatalogVendorBlocksTopcategories': LazyComponent<typeof import("../../app/components/catalog/vendor/blocks/topcategories.vue")['default']>
  'LazyCatalogVendorBlocksTopproducts': LazyComponent<typeof import("../../app/components/catalog/vendor/blocks/topproducts.vue")['default']>
  'LazyCatalogVendorPagesAttributes': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/attributes.vue")['default']>
  'LazyCatalogVendorPagesCommissions': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/commissions.vue")['default']>
  'LazyCatalogVendorPagesCrm': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/crm.vue")['default']>
  'LazyCatalogVendorPagesDashboard': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/dashboard.vue")['default']>
  'LazyCatalogVendorPagesEmails': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/emails.vue")['default']>
  'LazyCatalogVendorPagesEnquiries': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/enquiries.vue")['default']>
  'LazyCatalogVendorPagesInvoices': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/invoices.vue")['default']>
  'LazyCatalogVendorPagesOrders': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/orders.vue")['default']>
  'LazyCatalogVendorPagesProducts': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/products.vue")['default']>
  'LazyCatalogVendorPagesReviews': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/reviews.vue")['default']>
  'LazyCatalogVendorPagesShipments': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/shipments.vue")['default']>
  'LazyCatalogVendorPagesStores': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/stores.vue")['default']>
  'LazyContentBlocksBreadcrumbs': LazyComponent<typeof import("../../app/components/content/blocks/breadcrumbs.vue")['default']>
  'LazyContentBlocksCurrencySwitcher': LazyComponent<typeof import("../../app/components/content/blocks/currencySwitcher.vue")['default']>
  'LazyContentBlocksLanguageSwitcher': LazyComponent<typeof import("../../app/components/content/blocks/languageSwitcher.vue")['default']>
  'LazyContentBlocksVideoproduct': LazyComponent<typeof import("../../app/components/content/blocks/videoproduct.vue")['default']>
  'LazyEcosystemmenu': LazyComponent<typeof import("../../app/components/ecosystemmenu.vue")['default']>
  'LazyMarketingAddCoupon': LazyComponent<typeof import("../../app/components/marketing/add-coupon.vue")['default']>
  'LazyMarketingAddRewards': LazyComponent<typeof import("../../app/components/marketing/add-rewards.vue")['default']>
  'LazyMarketingCoupons': LazyComponent<typeof import("../../app/components/marketing/coupons.vue")['default']>
  'LazyMarketingPromotionsCoupons': LazyComponent<typeof import("../../app/components/marketing/promotions/coupons.vue")['default']>
  'LazyMarketingPromotionsGiftcard[id]': LazyComponent<typeof import("../../app/components/marketing/promotions/giftcard/[id].vue")['default']>
  'LazyMarketingPromotionsGiftcardReload': LazyComponent<typeof import("../../app/components/marketing/promotions/giftcard/reload.vue")['default']>
  'LazyMarketingPromotionsGiftcards': LazyComponent<typeof import("../../app/components/marketing/promotions/giftcards.vue")['default']>
  'LazyMarketingPromotionsSubscription[id]': LazyComponent<typeof import("../../app/components/marketing/promotions/subscription/[id].vue")['default']>
  'LazyMarketingPromotionsSubscriptions': LazyComponent<typeof import("../../app/components/marketing/promotions/subscriptions.vue")['default']>
  'LazyMarketingUpdateRewards': LazyComponent<typeof import("../../app/components/marketing/update-rewards.vue")['default']>
  'LazyMenusLowernav': LazyComponent<typeof import("../../app/components/menus/lowernav.vue")['default']>
  'LazyPartialsLocaleSelector': LazyComponent<typeof import("../../app/components/partials/LocaleSelector.vue")['default']>
  'LazyPartialsStripePayment': LazyComponent<typeof import("../../app/components/partials/StripePayment.vue")['default']>
  'LazyPartialsAddToCartBtn': LazyComponent<typeof import("../../app/components/partials/addToCartBtn.vue")['default']>
  'LazyPartialsCartItem': LazyComponent<typeof import("../../app/components/partials/cartItem.vue")['default']>
  'LazyPartialsCheckoutButton': LazyComponent<typeof import("../../app/components/partials/checkoutButton.vue")['default']>
  'LazyPartialsCompareBtn': LazyComponent<typeof import("../../app/components/partials/compareBtn.vue")['default']>
  'LazyPartialsRatings': LazyComponent<typeof import("../../app/components/partials/ratings.vue")['default']>
  'LazyPartialsStoreCurrencySelector': LazyComponent<typeof import("../../app/components/partials/store/CurrencySelector.vue")['default']>
  'LazyPartialsStoreSwitcher': LazyComponent<typeof import("../../app/components/partials/store/StoreSwitcher.vue")['default']>
  'LazyRelatedRelatedposts': LazyComponent<typeof import("../../app/components/related/relatedposts.vue")['default']>
  'LazyRelatedRelatedproducts': LazyComponent<typeof import("../../app/components/related/relatedproducts.vue")['default']>
  'LazySalesOrderDetailsDialog': LazyComponent<typeof import("../../app/components/sales/OrderDetailsDialog.vue")['default']>
  'LazySalesOrderManagement': LazyComponent<typeof import("../../app/components/sales/OrderManagement.vue")['default']>
  'LazySalesReceiptsTab': LazyComponent<typeof import("../../app/components/sales/ReceiptsTab.vue")['default']>
  'LazySalesReturnRequestDialog': LazyComponent<typeof import("../../app/components/sales/ReturnRequestDialog.vue")['default']>
  'LazySalesReturnsTab': LazyComponent<typeof import("../../app/components/sales/ReturnsTab.vue")['default']>
  'LazySalesTransactionsTab': LazyComponent<typeof import("../../app/components/sales/TransactionsTab.vue")['default']>
  'LazySalesBrandsRelatedbrands': LazyComponent<typeof import("../../app/components/sales/brands/relatedbrands.vue")['default']>
  'LazySalesCreditMemos': LazyComponent<typeof import("../../app/components/sales/creditMemos.vue")['default']>
  'LazySalesInvoices': LazyComponent<typeof import("../../app/components/sales/invoices.vue")['default']>
  'LazySalesOrdersAgreements': LazyComponent<typeof import("../../app/components/sales/orders/agreements.vue")['default']>
  'LazySalesOrdersCreditmemo[id]': LazyComponent<typeof import("../../app/components/sales/orders/creditmemo/[id].vue")['default']>
  'LazySalesOrdersCreditmemos': LazyComponent<typeof import("../../app/components/sales/orders/creditmemos.vue")['default']>
  'LazySalesOrdersInvoice[id]': LazyComponent<typeof import("../../app/components/sales/orders/invoice/[id].vue")['default']>
  'LazySalesOrdersInvoices': LazyComponent<typeof import("../../app/components/sales/orders/invoices.vue")['default']>
  'LazySalesOrdersMyOrder[id]': LazyComponent<typeof import("../../app/components/sales/orders/my-order/[id].vue")['default']>
  'LazySalesOrdersMyOrders': LazyComponent<typeof import("../../app/components/sales/orders/my-orders.vue")['default']>
  'LazySalesOrdersPayments': LazyComponent<typeof import("../../app/components/sales/orders/payments.vue")['default']>
  'LazySalesOrdersReturn': LazyComponent<typeof import("../../app/components/sales/orders/return.vue")['default']>
  'LazySalesOrdersReturns': LazyComponent<typeof import("../../app/components/sales/orders/returns.vue")['default']>
  'LazySalesOrdersShipment[id]': LazyComponent<typeof import("../../app/components/sales/orders/shipment/[id].vue")['default']>
  'LazySalesOrdersShipments': LazyComponent<typeof import("../../app/components/sales/orders/shipments.vue")['default']>
  'LazySalesOrdersTransaction[id]': LazyComponent<typeof import("../../app/components/sales/orders/transaction/[id].vue")['default']>
  'LazySalesOrdersTransactions': LazyComponent<typeof import("../../app/components/sales/orders/transactions.vue")['default']>
  'LazySalesOrdersTab': LazyComponent<typeof import("../../app/components/sales/ordersTab.vue")['default']>
  'LazySalesPaymentsPriceDisplay': LazyComponent<typeof import("../../app/components/sales/payments/PriceDisplay.vue")['default']>
  'LazySalesPaymentsStripePaymentElement': LazyComponent<typeof import("../../app/components/sales/payments/StripePaymentElement.vue")['default']>
  'LazySearch': LazyComponent<typeof import("../../app/components/search/search.vue")['default']>
  'LazyShopCartItem': LazyComponent<typeof import("../../app/components/shop/cart/cartItem.vue")['default']>
  'LazyShopCartCheckout': LazyComponent<typeof import("../../app/components/shop/cart/checkout.vue")['default']>
  'LazyShopCheckoutStripeCardElement': LazyComponent<typeof import("../../app/components/shop/checkout/StripeCardElement.vue")['default']>
  'LazyShopCheckoutStripeCheckout': LazyComponent<typeof import("../../app/components/shop/checkout/StripeCheckout.vue")['default']>
  'LazyShopCheckoutAddressBilling': LazyComponent<typeof import("../../app/components/shop/checkout/addressBilling.vue")['default']>
  'LazyShopCheckoutAddressShipping': LazyComponent<typeof import("../../app/components/shop/checkout/addressShipping.vue")['default']>
  'LazyShopCheckoutCartProductItem': LazyComponent<typeof import("../../app/components/shop/checkout/cart/ProductItem.vue")['default']>
  'LazyShopCheckoutCartPromotionItem': LazyComponent<typeof import("../../app/components/shop/checkout/cart/PromotionItem.vue")['default']>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
  'LazySfAccordionItem': LazyComponent<typeof import("@storefront-ui/vue")['SfAccordionItem']>
  'LazySfBadge': LazyComponent<typeof import("@storefront-ui/vue")['SfBadge']>
  'LazySfButton': LazyComponent<typeof import("@storefront-ui/vue")['SfButton']>
  'LazySfCheckbox': LazyComponent<typeof import("@storefront-ui/vue")['SfCheckbox']>
  'LazySfChip': LazyComponent<typeof import("@storefront-ui/vue")['SfChip']>
  'LazySfCounter': LazyComponent<typeof import("@storefront-ui/vue")['SfCounter']>
  'LazySfDrawer': LazyComponent<typeof import("@storefront-ui/vue")['SfDrawer']>
  'LazySfDropdown': LazyComponent<typeof import("@storefront-ui/vue")['SfDropdown']>
  'LazySfIconAdd': LazyComponent<typeof import("@storefront-ui/vue")['SfIconAdd']>
  'LazySfIconAddShoppingCart': LazyComponent<typeof import("@storefront-ui/vue")['SfIconAddShoppingCart']>
  'LazySfIconAlokai': LazyComponent<typeof import("@storefront-ui/vue")['SfIconAlokai']>
  'LazySfIconAlokaiFull': LazyComponent<typeof import("@storefront-ui/vue")['SfIconAlokaiFull']>
  'LazySfIconArrowBack': LazyComponent<typeof import("@storefront-ui/vue")['SfIconArrowBack']>
  'LazySfIconArrowDownward': LazyComponent<typeof import("@storefront-ui/vue")['SfIconArrowDownward']>
  'LazySfIconArrowForward': LazyComponent<typeof import("@storefront-ui/vue")['SfIconArrowForward']>
  'LazySfIconArrowUpward': LazyComponent<typeof import("@storefront-ui/vue")['SfIconArrowUpward']>
  'LazySfIconBase': LazyComponent<typeof import("@storefront-ui/vue")['SfIconBase']>
  'LazySfIconBlock': LazyComponent<typeof import("@storefront-ui/vue")['SfIconBlock']>
  'LazySfIconCalendarToday': LazyComponent<typeof import("@storefront-ui/vue")['SfIconCalendarToday']>
  'LazySfIconCall': LazyComponent<typeof import("@storefront-ui/vue")['SfIconCall']>
  'LazySfIconCancel': LazyComponent<typeof import("@storefront-ui/vue")['SfIconCancel']>
  'LazySfIconCheck': LazyComponent<typeof import("@storefront-ui/vue")['SfIconCheck']>
  'LazySfIconCheckBox': LazyComponent<typeof import("@storefront-ui/vue")['SfIconCheckBox']>
  'LazySfIconCheckBoxOutlineBlank': LazyComponent<typeof import("@storefront-ui/vue")['SfIconCheckBoxOutlineBlank']>
  'LazySfIconCheckCircle': LazyComponent<typeof import("@storefront-ui/vue")['SfIconCheckCircle']>
  'LazySfIconChevronLeft': LazyComponent<typeof import("@storefront-ui/vue")['SfIconChevronLeft']>
  'LazySfIconChevronRight': LazyComponent<typeof import("@storefront-ui/vue")['SfIconChevronRight']>
  'LazySfIconCircle': LazyComponent<typeof import("@storefront-ui/vue")['SfIconCircle']>
  'LazySfIconClose': LazyComponent<typeof import("@storefront-ui/vue")['SfIconClose']>
  'LazySfIconCloseSm': LazyComponent<typeof import("@storefront-ui/vue")['SfIconCloseSm']>
  'LazySfIconCompareArrows': LazyComponent<typeof import("@storefront-ui/vue")['SfIconCompareArrows']>
  'LazySfIconContactSupport': LazyComponent<typeof import("@storefront-ui/vue")['SfIconContactSupport']>
  'LazySfIconCreditCard': LazyComponent<typeof import("@storefront-ui/vue")['SfIconCreditCard']>
  'LazySfIconDelete': LazyComponent<typeof import("@storefront-ui/vue")['SfIconDelete']>
  'LazySfIconDownload': LazyComponent<typeof import("@storefront-ui/vue")['SfIconDownload']>
  'LazySfIconEmail': LazyComponent<typeof import("@storefront-ui/vue")['SfIconEmail']>
  'LazySfIconError': LazyComponent<typeof import("@storefront-ui/vue")['SfIconError']>
  'LazySfIconExpandLess': LazyComponent<typeof import("@storefront-ui/vue")['SfIconExpandLess']>
  'LazySfIconExpandMore': LazyComponent<typeof import("@storefront-ui/vue")['SfIconExpandMore']>
  'LazySfIconFacebook': LazyComponent<typeof import("@storefront-ui/vue")['SfIconFacebook']>
  'LazySfIconFavorite': LazyComponent<typeof import("@storefront-ui/vue")['SfIconFavorite']>
  'LazySfIconFavoriteFilled': LazyComponent<typeof import("@storefront-ui/vue")['SfIconFavoriteFilled']>
  'LazySfIconGridView': LazyComponent<typeof import("@storefront-ui/vue")['SfIconGridView']>
  'LazySfIconHelp': LazyComponent<typeof import("@storefront-ui/vue")['SfIconHelp']>
  'LazySfIconHome': LazyComponent<typeof import("@storefront-ui/vue")['SfIconHome']>
  'LazySfIconIndeterminateCheckBox': LazyComponent<typeof import("@storefront-ui/vue")['SfIconIndeterminateCheckBox']>
  'LazySfIconInfo': LazyComponent<typeof import("@storefront-ui/vue")['SfIconInfo']>
  'LazySfIconInstagram': LazyComponent<typeof import("@storefront-ui/vue")['SfIconInstagram']>
  'LazySfIconLanguage': LazyComponent<typeof import("@storefront-ui/vue")['SfIconLanguage']>
  'LazySfIconLocalShipping': LazyComponent<typeof import("@storefront-ui/vue")['SfIconLocalShipping']>
  'LazySfIconLocalFireDepartment': LazyComponent<typeof import("@storefront-ui/vue")['SfIconLocal_fire_department']>
  'LazySfIconLocationOn': LazyComponent<typeof import("@storefront-ui/vue")['SfIconLocationOn']>
  'LazySfIconLocationOnFilled': LazyComponent<typeof import("@storefront-ui/vue")['SfIconLocationOnFilled']>
  'LazySfIconLock': LazyComponent<typeof import("@storefront-ui/vue")['SfIconLock']>
  'LazySfIconLockOpen': LazyComponent<typeof import("@storefront-ui/vue")['SfIconLockOpen']>
  'LazySfIconLogin': LazyComponent<typeof import("@storefront-ui/vue")['SfIconLogin']>
  'LazySfIconLogout': LazyComponent<typeof import("@storefront-ui/vue")['SfIconLogout']>
  'LazySfIconMenu': LazyComponent<typeof import("@storefront-ui/vue")['SfIconMenu']>
  'LazySfIconMoreHoriz': LazyComponent<typeof import("@storefront-ui/vue")['SfIconMoreHoriz']>
  'LazySfIconMoreVert': LazyComponent<typeof import("@storefront-ui/vue")['SfIconMoreVert']>
  'LazySfIconOpenInNew': LazyComponent<typeof import("@storefront-ui/vue")['SfIconOpenInNew']>
  'LazySfIconOpenSource': LazyComponent<typeof import("@storefront-ui/vue")['SfIconOpenSource']>
  'LazySfIconPackage': LazyComponent<typeof import("@storefront-ui/vue")['SfIconPackage']>
  'LazySfIconPercent': LazyComponent<typeof import("@storefront-ui/vue")['SfIconPercent']>
  'LazySfIconPerson': LazyComponent<typeof import("@storefront-ui/vue")['SfIconPerson']>
  'LazySfIconPinterest': LazyComponent<typeof import("@storefront-ui/vue")['SfIconPinterest']>
  'LazySfIconPublishedWithChanges': LazyComponent<typeof import("@storefront-ui/vue")['SfIconPublishedWithChanges']>
  'LazySfIconRadioButtonChecked': LazyComponent<typeof import("@storefront-ui/vue")['SfIconRadioButtonChecked']>
  'LazySfIconRadioButtonUnchecked': LazyComponent<typeof import("@storefront-ui/vue")['SfIconRadioButtonUnchecked']>
  'LazySfIconReact': LazyComponent<typeof import("@storefront-ui/vue")['SfIconReact']>
  'LazySfIconRemove': LazyComponent<typeof import("@storefront-ui/vue")['SfIconRemove']>
  'LazySfIconRemoveShoppingCart': LazyComponent<typeof import("@storefront-ui/vue")['SfIconRemoveShoppingCart']>
  'LazySfIconSafetyCheck': LazyComponent<typeof import("@storefront-ui/vue")['SfIconSafetyCheck']>
  'LazySfIconSchedule': LazyComponent<typeof import("@storefront-ui/vue")['SfIconSchedule']>
  'LazySfIconSearch': LazyComponent<typeof import("@storefront-ui/vue")['SfIconSearch']>
  'LazySfIconSell': LazyComponent<typeof import("@storefront-ui/vue")['SfIconSell']>
  'LazySfIconShare': LazyComponent<typeof import("@storefront-ui/vue")['SfIconShare']>
  'LazySfIconShoppingCart': LazyComponent<typeof import("@storefront-ui/vue")['SfIconShoppingCart']>
  'LazySfIconShoppingCartCheckout': LazyComponent<typeof import("@storefront-ui/vue")['SfIconShoppingCartCheckout']>
  'LazySfIconSort': LazyComponent<typeof import("@storefront-ui/vue")['SfIconSort']>
  'LazySfIconStar': LazyComponent<typeof import("@storefront-ui/vue")['SfIconStar']>
  'LazySfIconStarFilled': LazyComponent<typeof import("@storefront-ui/vue")['SfIconStarFilled']>
  'LazySfIconStarHalf': LazyComponent<typeof import("@storefront-ui/vue")['SfIconStarHalf']>
  'LazySfIconThumbDown': LazyComponent<typeof import("@storefront-ui/vue")['SfIconThumbDown']>
  'LazySfIconThumbUp': LazyComponent<typeof import("@storefront-ui/vue")['SfIconThumbUp']>
  'LazySfIconTune': LazyComponent<typeof import("@storefront-ui/vue")['SfIconTune']>
  'LazySfIconTwitter': LazyComponent<typeof import("@storefront-ui/vue")['SfIconTwitter']>
  'LazySfIconUndo': LazyComponent<typeof import("@storefront-ui/vue")['SfIconUndo']>
  'LazySfIconUnfoldMore': LazyComponent<typeof import("@storefront-ui/vue")['SfIconUnfoldMore']>
  'LazySfIconUpload': LazyComponent<typeof import("@storefront-ui/vue")['SfIconUpload']>
  'LazySfIconViewList': LazyComponent<typeof import("@storefront-ui/vue")['SfIconViewList']>
  'LazySfIconVisibility': LazyComponent<typeof import("@storefront-ui/vue")['SfIconVisibility']>
  'LazySfIconVisibilityOff': LazyComponent<typeof import("@storefront-ui/vue")['SfIconVisibilityOff']>
  'LazySfIconVsfDiamond': LazyComponent<typeof import("@storefront-ui/vue")['SfIconVsfDiamond']>
  'LazySfIconVuejs': LazyComponent<typeof import("@storefront-ui/vue")['SfIconVuejs']>
  'LazySfIconVuestorefront': LazyComponent<typeof import("@storefront-ui/vue")['SfIconVuestorefront']>
  'LazySfIconWarehouse': LazyComponent<typeof import("@storefront-ui/vue")['SfIconWarehouse']>
  'LazySfIconWarning': LazyComponent<typeof import("@storefront-ui/vue")['SfIconWarning']>
  'LazySfIconYoutube': LazyComponent<typeof import("@storefront-ui/vue")['SfIconYoutube']>
  'LazySfInput': LazyComponent<typeof import("@storefront-ui/vue")['SfInput']>
  'LazySfLink': LazyComponent<typeof import("@storefront-ui/vue")['SfLink']>
  'LazySfListItem': LazyComponent<typeof import("@storefront-ui/vue")['SfListItem']>
  'LazySfLoaderCircular': LazyComponent<typeof import("@storefront-ui/vue")['SfLoaderCircular']>
  'LazySfLoaderLinear': LazyComponent<typeof import("@storefront-ui/vue")['SfLoaderLinear']>
  'LazySfModal': LazyComponent<typeof import("@storefront-ui/vue")['SfModal']>
  'LazySfProgressCircular': LazyComponent<typeof import("@storefront-ui/vue")['SfProgressCircular']>
  'LazySfProgressLinear': LazyComponent<typeof import("@storefront-ui/vue")['SfProgressLinear']>
  'LazySfRadio': LazyComponent<typeof import("@storefront-ui/vue")['SfRadio']>
  'LazySfRating': LazyComponent<typeof import("@storefront-ui/vue")['SfRating']>
  'LazySfRatingButton': LazyComponent<typeof import("@storefront-ui/vue")['SfRatingButton']>
  'LazySfScrollable': LazyComponent<typeof import("@storefront-ui/vue")['SfScrollable']>
  'LazySfSelect': LazyComponent<typeof import("@storefront-ui/vue")['SfSelect']>
  'LazySfSwitch': LazyComponent<typeof import("@storefront-ui/vue")['SfSwitch']>
  'LazySfTextarea': LazyComponent<typeof import("@storefront-ui/vue")['SfTextarea']>
  'LazySfThumbnail': LazyComponent<typeof import("@storefront-ui/vue")['SfThumbnail']>
  'LazySfTooltip': LazyComponent<typeof import("@storefront-ui/vue")['SfTooltip']>
  'LazyNuxtLinkLocale': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
  'LazySwitchLocalePathLink': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
