
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const CatalogProductAddAttribute: typeof import("../app/components/catalog/product/add-attribute.vue").default
export const CatalogProductAddProductType: typeof import("../app/components/catalog/product/add-product-type.vue").default
export const CatalogProductAddProduct: typeof import("../app/components/catalog/product/add-product.vue").default
export const CatalogProductAddShowcase: typeof import("../app/components/catalog/product/add-showcase.vue").default
export const CatalogProductAddStation: typeof import("../app/components/catalog/product/add-station.vue").default
export const CatalogProductBestsellers: typeof import("../app/components/catalog/product/bestsellers.vue").default
export const CatalogProductBrands: typeof import("../app/components/catalog/product/brands.vue").default
export const CatalogProductColorOptions: typeof import("../app/components/catalog/product/colorOptions.vue").default
export const CatalogProductDeals: typeof import("../app/components/catalog/product/deals.vue").default
export const CatalogProductExclusives: typeof import("../app/components/catalog/product/exclusives.vue").default
export const CatalogProductFeaturedproducts: typeof import("../app/components/catalog/product/featuredproducts.vue").default
export const CatalogProductGiftCard: typeof import("../app/components/catalog/product/giftCard.vue").default
export const CatalogProductLatestproducts: typeof import("../app/components/catalog/product/latestproducts.vue").default
export const CatalogProductCard: typeof import("../app/components/catalog/product/productCard.vue").default
export const CatalogProductCompare: typeof import("../app/components/catalog/product/productCompare.vue").default
export const CatalogProductCompareTable: typeof import("../app/components/catalog/product/productCompareTable.vue").default
export const CatalogProductDetails: typeof import("../app/components/catalog/product/productDetails.vue").default
export const CatalogProductFaqs: typeof import("../app/components/catalog/product/productFaqs.vue").default
export const CatalogProductGallery: typeof import("../app/components/catalog/product/productGallery.vue").default
export const CatalogProductQty: typeof import("../app/components/catalog/product/productQty.vue").default
export const CatalogProductReviews: typeof import("../app/components/catalog/product/productReviews.vue").default
export const CatalogProductSpecs: typeof import("../app/components/catalog/product/productSpecs.vue").default
export const CatalogProductRadiostation: typeof import("../app/components/catalog/product/radiostation.vue").default
export const CatalogProductRecentlyviewed: typeof import("../app/components/catalog/product/recentlyviewed.vue").default
export const CatalogProductRelatedproducts: typeof import("../app/components/catalog/product/relatedproducts.vue").default
export const CatalogProductRelatedstations: typeof import("../app/components/catalog/product/relatedstations.vue").default
export const CatalogProductShippingOptions: typeof import("../app/components/catalog/product/shippingOptions.vue").default
export const CatalogProductSizeOptions: typeof import("../app/components/catalog/product/sizeOptions.vue").default
export const CatalogProductUpdateAttributeSet: typeof import("../app/components/catalog/product/update-attribute-set.vue").default
export const CatalogProductUpdateAttribute: typeof import("../app/components/catalog/product/update-attribute.vue").default
export const CatalogProductUpdateProduct: typeof import("../app/components/catalog/product/update-product.vue").default
export const CatalogProductUpdateShowcase: typeof import("../app/components/catalog/product/update-showcase.vue").default
export const CatalogShopsRelatedstores: typeof import("../app/components/catalog/shops/relatedstores.vue").default
export const CatalogShopsRestaurant: typeof import("../app/components/catalog/shops/restaurant.vue").default
export const CatalogShopsStores: typeof import("../app/components/catalog/shops/stores.vue").default
export const CatalogVendorBlocksBiggestcustomers: typeof import("../app/components/catalog/vendor/blocks/biggestcustomers.vue").default
export const CatalogVendorBlocksLowestselling: typeof import("../app/components/catalog/vendor/blocks/lowestselling.vue").default
export const CatalogVendorBlocksTopcategories: typeof import("../app/components/catalog/vendor/blocks/topcategories.vue").default
export const CatalogVendorBlocksTopproducts: typeof import("../app/components/catalog/vendor/blocks/topproducts.vue").default
export const CatalogVendorPagesAttributes: typeof import("../app/components/catalog/vendor/pages/attributes.vue").default
export const CatalogVendorPagesCommissions: typeof import("../app/components/catalog/vendor/pages/commissions.vue").default
export const CatalogVendorPagesCrm: typeof import("../app/components/catalog/vendor/pages/crm.vue").default
export const CatalogVendorPagesDashboard: typeof import("../app/components/catalog/vendor/pages/dashboard.vue").default
export const CatalogVendorPagesEmails: typeof import("../app/components/catalog/vendor/pages/emails.vue").default
export const CatalogVendorPagesEnquiries: typeof import("../app/components/catalog/vendor/pages/enquiries.vue").default
export const CatalogVendorPagesInvoices: typeof import("../app/components/catalog/vendor/pages/invoices.vue").default
export const CatalogVendorPagesOrders: typeof import("../app/components/catalog/vendor/pages/orders.vue").default
export const CatalogVendorPagesProducts: typeof import("../app/components/catalog/vendor/pages/products.vue").default
export const CatalogVendorPagesReviews: typeof import("../app/components/catalog/vendor/pages/reviews.vue").default
export const CatalogVendorPagesShipments: typeof import("../app/components/catalog/vendor/pages/shipments.vue").default
export const CatalogVendorPagesStores: typeof import("../app/components/catalog/vendor/pages/stores.vue").default
export const ContentBlocksBreadcrumbs: typeof import("../app/components/content/blocks/breadcrumbs.vue").default
export const ContentBlocksCurrencySwitcher: typeof import("../app/components/content/blocks/currencySwitcher.vue").default
export const ContentBlocksLanguageSwitcher: typeof import("../app/components/content/blocks/languageSwitcher.vue").default
export const ContentBlocksVideoproduct: typeof import("../app/components/content/blocks/videoproduct.vue").default
export const ContentPagesShowcases: typeof import("../app/components/content/pages/showcases.vue").default
export const MarketingAddBrand: typeof import("../app/components/marketing/add-brand.vue").default
export const MarketingAddCoupon: typeof import("../app/components/marketing/add-coupon.vue").default
export const MarketingAddRewards: typeof import("../app/components/marketing/add-rewards.vue").default
export const MarketingCoupons: typeof import("../app/components/marketing/coupons.vue").default
export const MarketingPromotionsCoupons: typeof import("../app/components/marketing/promotions/coupons.vue").default
export const MarketingPromotionsGiftcard[id]: typeof import("../app/components/marketing/promotions/giftcard/[id].vue").default
export const MarketingPromotionsGiftcardReload: typeof import("../app/components/marketing/promotions/giftcard/reload.vue").default
export const MarketingPromotionsGiftcards: typeof import("../app/components/marketing/promotions/giftcards.vue").default
export const MarketingPromotionsSubscription[id]: typeof import("../app/components/marketing/promotions/subscription/[id].vue").default
export const MarketingPromotionsSubscriptions: typeof import("../app/components/marketing/promotions/subscriptions.vue").default
export const MarketingUpdateRewards: typeof import("../app/components/marketing/update-rewards.vue").default
export const MenusLowernav: typeof import("../app/components/menus/lowernav.vue").default
export const PartialsLocaleSelector: typeof import("../app/components/partials/LocaleSelector.vue").default
export const PartialsShoppingCart: typeof import("../app/components/partials/ShoppingCart.vue").default
export const PartialsStripePayment: typeof import("../app/components/partials/StripePayment.vue").default
export const PartialsAddToCartBtn: typeof import("../app/components/partials/addToCartBtn.vue").default
export const PartialsCartItem: typeof import("../app/components/partials/cartItem.vue").default
export const PartialsCheckoutButton: typeof import("../app/components/partials/checkoutButton.vue").default
export const PartialsCompareBtn: typeof import("../app/components/partials/compareBtn.vue").default
export const PartialsRatings: typeof import("../app/components/partials/ratings.vue").default
export const PartialsStoreCurrencySelector: typeof import("../app/components/partials/store/CurrencySelector.vue").default
export const PartialsStoreSwitcher: typeof import("../app/components/partials/store/StoreSwitcher.vue").default
export const RelatedRelatedposts: typeof import("../app/components/related/relatedposts.vue").default
export const RelatedRelatedproducts: typeof import("../app/components/related/relatedproducts.vue").default
export const SalesOrderDetailsDialog: typeof import("../app/components/sales/OrderDetailsDialog.vue").default
export const SalesOrderManagement: typeof import("../app/components/sales/OrderManagement.vue").default
export const SalesReceiptsTab: typeof import("../app/components/sales/ReceiptsTab.vue").default
export const SalesReturnRequestDialog: typeof import("../app/components/sales/ReturnRequestDialog.vue").default
export const SalesReturnsTab: typeof import("../app/components/sales/ReturnsTab.vue").default
export const SalesTransactionsTab: typeof import("../app/components/sales/TransactionsTab.vue").default
export const SalesBrandsRelatedbrands: typeof import("../app/components/sales/brands/relatedbrands.vue").default
export const SalesCreditMemos: typeof import("../app/components/sales/creditMemos.vue").default
export const SalesInvoices: typeof import("../app/components/sales/invoices.vue").default
export const SalesOrdersAgreements: typeof import("../app/components/sales/orders/agreements.vue").default
export const SalesOrdersCreditmemo[id]: typeof import("../app/components/sales/orders/creditmemo/[id].vue").default
export const SalesOrdersCreditmemos: typeof import("../app/components/sales/orders/creditmemos.vue").default
export const SalesOrdersInvoice[id]: typeof import("../app/components/sales/orders/invoice/[id].vue").default
export const SalesOrdersInvoices: typeof import("../app/components/sales/orders/invoices.vue").default
export const SalesOrdersMyOrder[id]: typeof import("../app/components/sales/orders/my-order/[id].vue").default
export const SalesOrdersMyOrders: typeof import("../app/components/sales/orders/my-orders.vue").default
export const SalesOrdersPayments: typeof import("../app/components/sales/orders/payments.vue").default
export const SalesOrdersReturn: typeof import("../app/components/sales/orders/return.vue").default
export const SalesOrdersReturns: typeof import("../app/components/sales/orders/returns.vue").default
export const SalesOrdersShipment[id]: typeof import("../app/components/sales/orders/shipment/[id].vue").default
export const SalesOrdersShipments: typeof import("../app/components/sales/orders/shipments.vue").default
export const SalesOrdersTransaction[id]: typeof import("../app/components/sales/orders/transaction/[id].vue").default
export const SalesOrdersTransactions: typeof import("../app/components/sales/orders/transactions.vue").default
export const SalesOrdersTab: typeof import("../app/components/sales/ordersTab.vue").default
export const SalesPaymentsPriceDisplay: typeof import("../app/components/sales/payments/PriceDisplay.vue").default
export const SalesPaymentsStripePaymentElement: typeof import("../app/components/sales/payments/StripePaymentElement.vue").default
export const ShopAddShop: typeof import("../app/components/shop/add-shop.vue").default
export const ShopCartItem: typeof import("../app/components/shop/cart/cartItem.vue").default
export const ShopCartCheckout: typeof import("../app/components/shop/cart/checkout.vue").default
export const ShopCheckoutStripeCardElement: typeof import("../app/components/shop/checkout/StripeCardElement.vue").default
export const ShopCheckoutStripeCheckout: typeof import("../app/components/shop/checkout/StripeCheckout.vue").default
export const ShopCheckoutAddressBilling: typeof import("../app/components/shop/checkout/addressBilling.vue").default
export const ShopCheckoutAddressShipping: typeof import("../app/components/shop/checkout/addressShipping.vue").default
export const ShopCheckoutCartProductItem: typeof import("../app/components/shop/checkout/cart/ProductItem.vue").default
export const ShopCheckoutCartPromotionItem: typeof import("../app/components/shop/checkout/cart/PromotionItem.vue").default
export const NuxtWelcome: typeof import("../../../node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../../../node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../../../node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
export const NuxtPicture: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
export const NuxtPage: typeof import("../../../node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyCatalogProductAddAttribute: LazyComponent<typeof import("../app/components/catalog/product/add-attribute.vue").default>
export const LazyCatalogProductAddProductType: LazyComponent<typeof import("../app/components/catalog/product/add-product-type.vue").default>
export const LazyCatalogProductAddProduct: LazyComponent<typeof import("../app/components/catalog/product/add-product.vue").default>
export const LazyCatalogProductAddShowcase: LazyComponent<typeof import("../app/components/catalog/product/add-showcase.vue").default>
export const LazyCatalogProductAddStation: LazyComponent<typeof import("../app/components/catalog/product/add-station.vue").default>
export const LazyCatalogProductBestsellers: LazyComponent<typeof import("../app/components/catalog/product/bestsellers.vue").default>
export const LazyCatalogProductBrands: LazyComponent<typeof import("../app/components/catalog/product/brands.vue").default>
export const LazyCatalogProductColorOptions: LazyComponent<typeof import("../app/components/catalog/product/colorOptions.vue").default>
export const LazyCatalogProductDeals: LazyComponent<typeof import("../app/components/catalog/product/deals.vue").default>
export const LazyCatalogProductExclusives: LazyComponent<typeof import("../app/components/catalog/product/exclusives.vue").default>
export const LazyCatalogProductFeaturedproducts: LazyComponent<typeof import("../app/components/catalog/product/featuredproducts.vue").default>
export const LazyCatalogProductGiftCard: LazyComponent<typeof import("../app/components/catalog/product/giftCard.vue").default>
export const LazyCatalogProductLatestproducts: LazyComponent<typeof import("../app/components/catalog/product/latestproducts.vue").default>
export const LazyCatalogProductCard: LazyComponent<typeof import("../app/components/catalog/product/productCard.vue").default>
export const LazyCatalogProductCompare: LazyComponent<typeof import("../app/components/catalog/product/productCompare.vue").default>
export const LazyCatalogProductCompareTable: LazyComponent<typeof import("../app/components/catalog/product/productCompareTable.vue").default>
export const LazyCatalogProductDetails: LazyComponent<typeof import("../app/components/catalog/product/productDetails.vue").default>
export const LazyCatalogProductFaqs: LazyComponent<typeof import("../app/components/catalog/product/productFaqs.vue").default>
export const LazyCatalogProductGallery: LazyComponent<typeof import("../app/components/catalog/product/productGallery.vue").default>
export const LazyCatalogProductQty: LazyComponent<typeof import("../app/components/catalog/product/productQty.vue").default>
export const LazyCatalogProductReviews: LazyComponent<typeof import("../app/components/catalog/product/productReviews.vue").default>
export const LazyCatalogProductSpecs: LazyComponent<typeof import("../app/components/catalog/product/productSpecs.vue").default>
export const LazyCatalogProductRadiostation: LazyComponent<typeof import("../app/components/catalog/product/radiostation.vue").default>
export const LazyCatalogProductRecentlyviewed: LazyComponent<typeof import("../app/components/catalog/product/recentlyviewed.vue").default>
export const LazyCatalogProductRelatedproducts: LazyComponent<typeof import("../app/components/catalog/product/relatedproducts.vue").default>
export const LazyCatalogProductRelatedstations: LazyComponent<typeof import("../app/components/catalog/product/relatedstations.vue").default>
export const LazyCatalogProductShippingOptions: LazyComponent<typeof import("../app/components/catalog/product/shippingOptions.vue").default>
export const LazyCatalogProductSizeOptions: LazyComponent<typeof import("../app/components/catalog/product/sizeOptions.vue").default>
export const LazyCatalogProductUpdateAttributeSet: LazyComponent<typeof import("../app/components/catalog/product/update-attribute-set.vue").default>
export const LazyCatalogProductUpdateAttribute: LazyComponent<typeof import("../app/components/catalog/product/update-attribute.vue").default>
export const LazyCatalogProductUpdateProduct: LazyComponent<typeof import("../app/components/catalog/product/update-product.vue").default>
export const LazyCatalogProductUpdateShowcase: LazyComponent<typeof import("../app/components/catalog/product/update-showcase.vue").default>
export const LazyCatalogShopsRelatedstores: LazyComponent<typeof import("../app/components/catalog/shops/relatedstores.vue").default>
export const LazyCatalogShopsRestaurant: LazyComponent<typeof import("../app/components/catalog/shops/restaurant.vue").default>
export const LazyCatalogShopsStores: LazyComponent<typeof import("../app/components/catalog/shops/stores.vue").default>
export const LazyCatalogVendorBlocksBiggestcustomers: LazyComponent<typeof import("../app/components/catalog/vendor/blocks/biggestcustomers.vue").default>
export const LazyCatalogVendorBlocksLowestselling: LazyComponent<typeof import("../app/components/catalog/vendor/blocks/lowestselling.vue").default>
export const LazyCatalogVendorBlocksTopcategories: LazyComponent<typeof import("../app/components/catalog/vendor/blocks/topcategories.vue").default>
export const LazyCatalogVendorBlocksTopproducts: LazyComponent<typeof import("../app/components/catalog/vendor/blocks/topproducts.vue").default>
export const LazyCatalogVendorPagesAttributes: LazyComponent<typeof import("../app/components/catalog/vendor/pages/attributes.vue").default>
export const LazyCatalogVendorPagesCommissions: LazyComponent<typeof import("../app/components/catalog/vendor/pages/commissions.vue").default>
export const LazyCatalogVendorPagesCrm: LazyComponent<typeof import("../app/components/catalog/vendor/pages/crm.vue").default>
export const LazyCatalogVendorPagesDashboard: LazyComponent<typeof import("../app/components/catalog/vendor/pages/dashboard.vue").default>
export const LazyCatalogVendorPagesEmails: LazyComponent<typeof import("../app/components/catalog/vendor/pages/emails.vue").default>
export const LazyCatalogVendorPagesEnquiries: LazyComponent<typeof import("../app/components/catalog/vendor/pages/enquiries.vue").default>
export const LazyCatalogVendorPagesInvoices: LazyComponent<typeof import("../app/components/catalog/vendor/pages/invoices.vue").default>
export const LazyCatalogVendorPagesOrders: LazyComponent<typeof import("../app/components/catalog/vendor/pages/orders.vue").default>
export const LazyCatalogVendorPagesProducts: LazyComponent<typeof import("../app/components/catalog/vendor/pages/products.vue").default>
export const LazyCatalogVendorPagesReviews: LazyComponent<typeof import("../app/components/catalog/vendor/pages/reviews.vue").default>
export const LazyCatalogVendorPagesShipments: LazyComponent<typeof import("../app/components/catalog/vendor/pages/shipments.vue").default>
export const LazyCatalogVendorPagesStores: LazyComponent<typeof import("../app/components/catalog/vendor/pages/stores.vue").default>
export const LazyContentBlocksBreadcrumbs: LazyComponent<typeof import("../app/components/content/blocks/breadcrumbs.vue").default>
export const LazyContentBlocksCurrencySwitcher: LazyComponent<typeof import("../app/components/content/blocks/currencySwitcher.vue").default>
export const LazyContentBlocksLanguageSwitcher: LazyComponent<typeof import("../app/components/content/blocks/languageSwitcher.vue").default>
export const LazyContentBlocksVideoproduct: LazyComponent<typeof import("../app/components/content/blocks/videoproduct.vue").default>
export const LazyContentPagesShowcases: LazyComponent<typeof import("../app/components/content/pages/showcases.vue").default>
export const LazyMarketingAddBrand: LazyComponent<typeof import("../app/components/marketing/add-brand.vue").default>
export const LazyMarketingAddCoupon: LazyComponent<typeof import("../app/components/marketing/add-coupon.vue").default>
export const LazyMarketingAddRewards: LazyComponent<typeof import("../app/components/marketing/add-rewards.vue").default>
export const LazyMarketingCoupons: LazyComponent<typeof import("../app/components/marketing/coupons.vue").default>
export const LazyMarketingPromotionsCoupons: LazyComponent<typeof import("../app/components/marketing/promotions/coupons.vue").default>
export const LazyMarketingPromotionsGiftcard[id]: LazyComponent<typeof import("../app/components/marketing/promotions/giftcard/[id].vue").default>
export const LazyMarketingPromotionsGiftcardReload: LazyComponent<typeof import("../app/components/marketing/promotions/giftcard/reload.vue").default>
export const LazyMarketingPromotionsGiftcards: LazyComponent<typeof import("../app/components/marketing/promotions/giftcards.vue").default>
export const LazyMarketingPromotionsSubscription[id]: LazyComponent<typeof import("../app/components/marketing/promotions/subscription/[id].vue").default>
export const LazyMarketingPromotionsSubscriptions: LazyComponent<typeof import("../app/components/marketing/promotions/subscriptions.vue").default>
export const LazyMarketingUpdateRewards: LazyComponent<typeof import("../app/components/marketing/update-rewards.vue").default>
export const LazyMenusLowernav: LazyComponent<typeof import("../app/components/menus/lowernav.vue").default>
export const LazyPartialsLocaleSelector: LazyComponent<typeof import("../app/components/partials/LocaleSelector.vue").default>
export const LazyPartialsShoppingCart: LazyComponent<typeof import("../app/components/partials/ShoppingCart.vue").default>
export const LazyPartialsStripePayment: LazyComponent<typeof import("../app/components/partials/StripePayment.vue").default>
export const LazyPartialsAddToCartBtn: LazyComponent<typeof import("../app/components/partials/addToCartBtn.vue").default>
export const LazyPartialsCartItem: LazyComponent<typeof import("../app/components/partials/cartItem.vue").default>
export const LazyPartialsCheckoutButton: LazyComponent<typeof import("../app/components/partials/checkoutButton.vue").default>
export const LazyPartialsCompareBtn: LazyComponent<typeof import("../app/components/partials/compareBtn.vue").default>
export const LazyPartialsRatings: LazyComponent<typeof import("../app/components/partials/ratings.vue").default>
export const LazyPartialsStoreCurrencySelector: LazyComponent<typeof import("../app/components/partials/store/CurrencySelector.vue").default>
export const LazyPartialsStoreSwitcher: LazyComponent<typeof import("../app/components/partials/store/StoreSwitcher.vue").default>
export const LazyRelatedRelatedposts: LazyComponent<typeof import("../app/components/related/relatedposts.vue").default>
export const LazyRelatedRelatedproducts: LazyComponent<typeof import("../app/components/related/relatedproducts.vue").default>
export const LazySalesOrderDetailsDialog: LazyComponent<typeof import("../app/components/sales/OrderDetailsDialog.vue").default>
export const LazySalesOrderManagement: LazyComponent<typeof import("../app/components/sales/OrderManagement.vue").default>
export const LazySalesReceiptsTab: LazyComponent<typeof import("../app/components/sales/ReceiptsTab.vue").default>
export const LazySalesReturnRequestDialog: LazyComponent<typeof import("../app/components/sales/ReturnRequestDialog.vue").default>
export const LazySalesReturnsTab: LazyComponent<typeof import("../app/components/sales/ReturnsTab.vue").default>
export const LazySalesTransactionsTab: LazyComponent<typeof import("../app/components/sales/TransactionsTab.vue").default>
export const LazySalesBrandsRelatedbrands: LazyComponent<typeof import("../app/components/sales/brands/relatedbrands.vue").default>
export const LazySalesCreditMemos: LazyComponent<typeof import("../app/components/sales/creditMemos.vue").default>
export const LazySalesInvoices: LazyComponent<typeof import("../app/components/sales/invoices.vue").default>
export const LazySalesOrdersAgreements: LazyComponent<typeof import("../app/components/sales/orders/agreements.vue").default>
export const LazySalesOrdersCreditmemo[id]: LazyComponent<typeof import("../app/components/sales/orders/creditmemo/[id].vue").default>
export const LazySalesOrdersCreditmemos: LazyComponent<typeof import("../app/components/sales/orders/creditmemos.vue").default>
export const LazySalesOrdersInvoice[id]: LazyComponent<typeof import("../app/components/sales/orders/invoice/[id].vue").default>
export const LazySalesOrdersInvoices: LazyComponent<typeof import("../app/components/sales/orders/invoices.vue").default>
export const LazySalesOrdersMyOrder[id]: LazyComponent<typeof import("../app/components/sales/orders/my-order/[id].vue").default>
export const LazySalesOrdersMyOrders: LazyComponent<typeof import("../app/components/sales/orders/my-orders.vue").default>
export const LazySalesOrdersPayments: LazyComponent<typeof import("../app/components/sales/orders/payments.vue").default>
export const LazySalesOrdersReturn: LazyComponent<typeof import("../app/components/sales/orders/return.vue").default>
export const LazySalesOrdersReturns: LazyComponent<typeof import("../app/components/sales/orders/returns.vue").default>
export const LazySalesOrdersShipment[id]: LazyComponent<typeof import("../app/components/sales/orders/shipment/[id].vue").default>
export const LazySalesOrdersShipments: LazyComponent<typeof import("../app/components/sales/orders/shipments.vue").default>
export const LazySalesOrdersTransaction[id]: LazyComponent<typeof import("../app/components/sales/orders/transaction/[id].vue").default>
export const LazySalesOrdersTransactions: LazyComponent<typeof import("../app/components/sales/orders/transactions.vue").default>
export const LazySalesOrdersTab: LazyComponent<typeof import("../app/components/sales/ordersTab.vue").default>
export const LazySalesPaymentsPriceDisplay: LazyComponent<typeof import("../app/components/sales/payments/PriceDisplay.vue").default>
export const LazySalesPaymentsStripePaymentElement: LazyComponent<typeof import("../app/components/sales/payments/StripePaymentElement.vue").default>
export const LazyShopAddShop: LazyComponent<typeof import("../app/components/shop/add-shop.vue").default>
export const LazyShopCartItem: LazyComponent<typeof import("../app/components/shop/cart/cartItem.vue").default>
export const LazyShopCartCheckout: LazyComponent<typeof import("../app/components/shop/cart/checkout.vue").default>
export const LazyShopCheckoutStripeCardElement: LazyComponent<typeof import("../app/components/shop/checkout/StripeCardElement.vue").default>
export const LazyShopCheckoutStripeCheckout: LazyComponent<typeof import("../app/components/shop/checkout/StripeCheckout.vue").default>
export const LazyShopCheckoutAddressBilling: LazyComponent<typeof import("../app/components/shop/checkout/addressBilling.vue").default>
export const LazyShopCheckoutAddressShipping: LazyComponent<typeof import("../app/components/shop/checkout/addressShipping.vue").default>
export const LazyShopCheckoutCartProductItem: LazyComponent<typeof import("../app/components/shop/checkout/cart/ProductItem.vue").default>
export const LazyShopCheckoutCartPromotionItem: LazyComponent<typeof import("../app/components/shop/checkout/cart/PromotionItem.vue").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
export const LazyNuxtPicture: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
export const LazyNuxtPage: LazyComponent<typeof import("../../../node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
