
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const FooterNav: typeof import("../app/components/FooterNav.vue")['default']
export const CatalogProductAddAttributeSet: typeof import("../app/components/catalog/product/add-attribute-set.vue")['default']
export const CatalogProductAddAttribute: typeof import("../app/components/catalog/product/add-attribute.vue")['default']
export const CatalogProductAddProduct: typeof import("../app/components/catalog/product/add-product.vue")['default']
export const CatalogProductAddShowcase: typeof import("../app/components/catalog/product/add-showcase.vue")['default']
export const CatalogProductAddStation: typeof import("../app/components/catalog/product/add-station.vue")['default']
export const CatalogProductBestsellers: typeof import("../app/components/catalog/product/bestsellers.vue")['default']
export const CatalogProductBrands: typeof import("../app/components/catalog/product/brands.vue")['default']
export const CatalogProductColorOptions: typeof import("../app/components/catalog/product/colorOptions.vue")['default']
export const CatalogProductDeals: typeof import("../app/components/catalog/product/deals.vue")['default']
export const CatalogProductExclusives: typeof import("../app/components/catalog/product/exclusives.vue")['default']
export const CatalogProductFeaturedproducts: typeof import("../app/components/catalog/product/featuredproducts.vue")['default']
export const CatalogProductGiftCard: typeof import("../app/components/catalog/product/giftCard.vue")['default']
export const CatalogProductLatestproducts: typeof import("../app/components/catalog/product/latestproducts.vue")['default']
export const CatalogProductCard: typeof import("../app/components/catalog/product/productCard.vue")['default']
export const CatalogProductCompare: typeof import("../app/components/catalog/product/productCompare.vue")['default']
export const CatalogProductCompareTable: typeof import("../app/components/catalog/product/productCompareTable.vue")['default']
export const CatalogProductDetails: typeof import("../app/components/catalog/product/productDetails.vue")['default']
export const CatalogProductFaqs: typeof import("../app/components/catalog/product/productFaqs.vue")['default']
export const CatalogProductGallery: typeof import("../app/components/catalog/product/productGallery.vue")['default']
export const CatalogProductQty: typeof import("../app/components/catalog/product/productQty.vue")['default']
export const CatalogProductReviews: typeof import("../app/components/catalog/product/productReviews.vue")['default']
export const CatalogProductSpecs: typeof import("../app/components/catalog/product/productSpecs.vue")['default']
export const CatalogProductRadiostation: typeof import("../app/components/catalog/product/radiostation.vue")['default']
export const CatalogProductRecentlyviewed: typeof import("../app/components/catalog/product/recentlyviewed.vue")['default']
export const CatalogProductRelatedproducts: typeof import("../app/components/catalog/product/relatedproducts.vue")['default']
export const CatalogProductRelatedstations: typeof import("../app/components/catalog/product/relatedstations.vue")['default']
export const CatalogProductShippingOptions: typeof import("../app/components/catalog/product/shippingOptions.vue")['default']
export const CatalogProductSizeOptions: typeof import("../app/components/catalog/product/sizeOptions.vue")['default']
export const CatalogProductUpdateAttributeSet: typeof import("../app/components/catalog/product/update-attribute-set.vue")['default']
export const CatalogProductUpdateAttribute: typeof import("../app/components/catalog/product/update-attribute.vue")['default']
export const CatalogProductUpdateProduct: typeof import("../app/components/catalog/product/update-product.vue")['default']
export const CatalogProductUpdateShowcase: typeof import("../app/components/catalog/product/update-showcase.vue")['default']
export const CatalogShopsRelatedstores: typeof import("../app/components/catalog/shops/relatedstores.vue")['default']
export const CatalogShopsRestaurant: typeof import("../app/components/catalog/shops/restaurant.vue")['default']
export const CatalogShopsStores: typeof import("../app/components/catalog/shops/stores.vue")['default']
export const CatalogVendorBlocksBiggestcustomers: typeof import("../app/components/catalog/vendor/blocks/biggestcustomers.vue")['default']
export const CatalogVendorBlocksLowestselling: typeof import("../app/components/catalog/vendor/blocks/lowestselling.vue")['default']
export const CatalogVendorBlocksTopcategories: typeof import("../app/components/catalog/vendor/blocks/topcategories.vue")['default']
export const CatalogVendorBlocksTopproducts: typeof import("../app/components/catalog/vendor/blocks/topproducts.vue")['default']
export const CatalogVendorPagesAttributes: typeof import("../app/components/catalog/vendor/pages/attributes.vue")['default']
export const CatalogVendorPagesCommissions: typeof import("../app/components/catalog/vendor/pages/commissions.vue")['default']
export const CatalogVendorPagesCrm: typeof import("../app/components/catalog/vendor/pages/crm.vue")['default']
export const CatalogVendorPagesDashboard: typeof import("../app/components/catalog/vendor/pages/dashboard.vue")['default']
export const CatalogVendorPagesEmails: typeof import("../app/components/catalog/vendor/pages/emails.vue")['default']
export const CatalogVendorPagesEnquiries: typeof import("../app/components/catalog/vendor/pages/enquiries.vue")['default']
export const CatalogVendorPagesInvoices: typeof import("../app/components/catalog/vendor/pages/invoices.vue")['default']
export const CatalogVendorPagesOrders: typeof import("../app/components/catalog/vendor/pages/orders.vue")['default']
export const CatalogVendorPagesProducts: typeof import("../app/components/catalog/vendor/pages/products.vue")['default']
export const CatalogVendorPagesReviews: typeof import("../app/components/catalog/vendor/pages/reviews.vue")['default']
export const CatalogVendorPagesShipments: typeof import("../app/components/catalog/vendor/pages/shipments.vue")['default']
export const CatalogVendorPagesStores: typeof import("../app/components/catalog/vendor/pages/stores.vue")['default']
export const ContentBlocksBreadcrumbs: typeof import("../app/components/content/blocks/breadcrumbs.vue")['default']
export const ContentBlocksCurrencySwitcher: typeof import("../app/components/content/blocks/currencySwitcher.vue")['default']
export const ContentBlocksLanguageSwitcher: typeof import("../app/components/content/blocks/languageSwitcher.vue")['default']
export const ContentBlocksVideoproduct: typeof import("../app/components/content/blocks/videoproduct.vue")['default']
export const Ecosystemmenu: typeof import("../app/components/ecosystemmenu.vue")['default']
export const MarketingAddCoupon: typeof import("../app/components/marketing/add-coupon.vue")['default']
export const MarketingAddRewards: typeof import("../app/components/marketing/add-rewards.vue")['default']
export const MarketingCoupons: typeof import("../app/components/marketing/coupons.vue")['default']
export const MarketingPromotionsCoupons: typeof import("../app/components/marketing/promotions/coupons.vue")['default']
export const MarketingPromotionsGiftcard[id]: typeof import("../app/components/marketing/promotions/giftcard/[id].vue")['default']
export const MarketingPromotionsGiftcardReload: typeof import("../app/components/marketing/promotions/giftcard/reload.vue")['default']
export const MarketingPromotionsGiftcards: typeof import("../app/components/marketing/promotions/giftcards.vue")['default']
export const MarketingPromotionsSubscription[id]: typeof import("../app/components/marketing/promotions/subscription/[id].vue")['default']
export const MarketingPromotionsSubscriptions: typeof import("../app/components/marketing/promotions/subscriptions.vue")['default']
export const MarketingUpdateRewards: typeof import("../app/components/marketing/update-rewards.vue")['default']
export const MenusLowernav: typeof import("../app/components/menus/lowernav.vue")['default']
export const PartialsLocaleSelector: typeof import("../app/components/partials/LocaleSelector.vue")['default']
export const PartialsStripePayment: typeof import("../app/components/partials/StripePayment.vue")['default']
export const PartialsAddToCartBtn: typeof import("../app/components/partials/addToCartBtn.vue")['default']
export const PartialsCartItem: typeof import("../app/components/partials/cartItem.vue")['default']
export const PartialsCheckoutButton: typeof import("../app/components/partials/checkoutButton.vue")['default']
export const PartialsCompareBtn: typeof import("../app/components/partials/compareBtn.vue")['default']
export const PartialsRatings: typeof import("../app/components/partials/ratings.vue")['default']
export const PartialsStoreCurrencySelector: typeof import("../app/components/partials/store/CurrencySelector.vue")['default']
export const PartialsStoreSwitcher: typeof import("../app/components/partials/store/StoreSwitcher.vue")['default']
export const RelatedRelatedposts: typeof import("../app/components/related/relatedposts.vue")['default']
export const RelatedRelatedproducts: typeof import("../app/components/related/relatedproducts.vue")['default']
export const SalesOrderDetailsDialog: typeof import("../app/components/sales/OrderDetailsDialog.vue")['default']
export const SalesOrderManagement: typeof import("../app/components/sales/OrderManagement.vue")['default']
export const SalesReceiptsTab: typeof import("../app/components/sales/ReceiptsTab.vue")['default']
export const SalesReturnRequestDialog: typeof import("../app/components/sales/ReturnRequestDialog.vue")['default']
export const SalesReturnsTab: typeof import("../app/components/sales/ReturnsTab.vue")['default']
export const SalesTransactionsTab: typeof import("../app/components/sales/TransactionsTab.vue")['default']
export const SalesBrandsRelatedbrands: typeof import("../app/components/sales/brands/relatedbrands.vue")['default']
export const SalesCreditMemos: typeof import("../app/components/sales/creditMemos.vue")['default']
export const SalesInvoices: typeof import("../app/components/sales/invoices.vue")['default']
export const SalesOrdersAgreements: typeof import("../app/components/sales/orders/agreements.vue")['default']
export const SalesOrdersCreditmemo[id]: typeof import("../app/components/sales/orders/creditmemo/[id].vue")['default']
export const SalesOrdersCreditmemos: typeof import("../app/components/sales/orders/creditmemos.vue")['default']
export const SalesOrdersInvoice[id]: typeof import("../app/components/sales/orders/invoice/[id].vue")['default']
export const SalesOrdersInvoices: typeof import("../app/components/sales/orders/invoices.vue")['default']
export const SalesOrdersMyOrder[id]: typeof import("../app/components/sales/orders/my-order/[id].vue")['default']
export const SalesOrdersMyOrders: typeof import("../app/components/sales/orders/my-orders.vue")['default']
export const SalesOrdersPayments: typeof import("../app/components/sales/orders/payments.vue")['default']
export const SalesOrdersReturn: typeof import("../app/components/sales/orders/return.vue")['default']
export const SalesOrdersReturns: typeof import("../app/components/sales/orders/returns.vue")['default']
export const SalesOrdersShipment[id]: typeof import("../app/components/sales/orders/shipment/[id].vue")['default']
export const SalesOrdersShipments: typeof import("../app/components/sales/orders/shipments.vue")['default']
export const SalesOrdersTransaction[id]: typeof import("../app/components/sales/orders/transaction/[id].vue")['default']
export const SalesOrdersTransactions: typeof import("../app/components/sales/orders/transactions.vue")['default']
export const SalesOrdersTab: typeof import("../app/components/sales/ordersTab.vue")['default']
export const SalesPaymentsPriceDisplay: typeof import("../app/components/sales/payments/PriceDisplay.vue")['default']
export const SalesPaymentsStripePaymentElement: typeof import("../app/components/sales/payments/StripePaymentElement.vue")['default']
export const Search: typeof import("../app/components/search/search.vue")['default']
export const ShopCartItem: typeof import("../app/components/shop/cart/cartItem.vue")['default']
export const ShopCartCheckout: typeof import("../app/components/shop/cart/checkout.vue")['default']
export const ShopCheckoutStripeCardElement: typeof import("../app/components/shop/checkout/StripeCardElement.vue")['default']
export const ShopCheckoutStripeCheckout: typeof import("../app/components/shop/checkout/StripeCheckout.vue")['default']
export const ShopCheckoutAddressBilling: typeof import("../app/components/shop/checkout/addressBilling.vue")['default']
export const ShopCheckoutAddressShipping: typeof import("../app/components/shop/checkout/addressShipping.vue")['default']
export const ShopCheckoutCartProductItem: typeof import("../app/components/shop/checkout/cart/ProductItem.vue")['default']
export const ShopCheckoutCartPromotionItem: typeof import("../app/components/shop/checkout/cart/PromotionItem.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const SfAccordionItem: typeof import("@storefront-ui/vue")['SfAccordionItem']
export const SfBadge: typeof import("@storefront-ui/vue")['SfBadge']
export const SfButton: typeof import("@storefront-ui/vue")['SfButton']
export const SfCheckbox: typeof import("@storefront-ui/vue")['SfCheckbox']
export const SfChip: typeof import("@storefront-ui/vue")['SfChip']
export const SfCounter: typeof import("@storefront-ui/vue")['SfCounter']
export const SfDrawer: typeof import("@storefront-ui/vue")['SfDrawer']
export const SfDropdown: typeof import("@storefront-ui/vue")['SfDropdown']
export const SfIconAdd: typeof import("@storefront-ui/vue")['SfIconAdd']
export const SfIconAddShoppingCart: typeof import("@storefront-ui/vue")['SfIconAddShoppingCart']
export const SfIconAlokai: typeof import("@storefront-ui/vue")['SfIconAlokai']
export const SfIconAlokaiFull: typeof import("@storefront-ui/vue")['SfIconAlokaiFull']
export const SfIconArrowBack: typeof import("@storefront-ui/vue")['SfIconArrowBack']
export const SfIconArrowDownward: typeof import("@storefront-ui/vue")['SfIconArrowDownward']
export const SfIconArrowForward: typeof import("@storefront-ui/vue")['SfIconArrowForward']
export const SfIconArrowUpward: typeof import("@storefront-ui/vue")['SfIconArrowUpward']
export const SfIconBase: typeof import("@storefront-ui/vue")['SfIconBase']
export const SfIconBlock: typeof import("@storefront-ui/vue")['SfIconBlock']
export const SfIconCalendarToday: typeof import("@storefront-ui/vue")['SfIconCalendarToday']
export const SfIconCall: typeof import("@storefront-ui/vue")['SfIconCall']
export const SfIconCancel: typeof import("@storefront-ui/vue")['SfIconCancel']
export const SfIconCheck: typeof import("@storefront-ui/vue")['SfIconCheck']
export const SfIconCheckBox: typeof import("@storefront-ui/vue")['SfIconCheckBox']
export const SfIconCheckBoxOutlineBlank: typeof import("@storefront-ui/vue")['SfIconCheckBoxOutlineBlank']
export const SfIconCheckCircle: typeof import("@storefront-ui/vue")['SfIconCheckCircle']
export const SfIconChevronLeft: typeof import("@storefront-ui/vue")['SfIconChevronLeft']
export const SfIconChevronRight: typeof import("@storefront-ui/vue")['SfIconChevronRight']
export const SfIconCircle: typeof import("@storefront-ui/vue")['SfIconCircle']
export const SfIconClose: typeof import("@storefront-ui/vue")['SfIconClose']
export const SfIconCloseSm: typeof import("@storefront-ui/vue")['SfIconCloseSm']
export const SfIconCompareArrows: typeof import("@storefront-ui/vue")['SfIconCompareArrows']
export const SfIconContactSupport: typeof import("@storefront-ui/vue")['SfIconContactSupport']
export const SfIconCreditCard: typeof import("@storefront-ui/vue")['SfIconCreditCard']
export const SfIconDelete: typeof import("@storefront-ui/vue")['SfIconDelete']
export const SfIconDownload: typeof import("@storefront-ui/vue")['SfIconDownload']
export const SfIconEmail: typeof import("@storefront-ui/vue")['SfIconEmail']
export const SfIconError: typeof import("@storefront-ui/vue")['SfIconError']
export const SfIconExpandLess: typeof import("@storefront-ui/vue")['SfIconExpandLess']
export const SfIconExpandMore: typeof import("@storefront-ui/vue")['SfIconExpandMore']
export const SfIconFacebook: typeof import("@storefront-ui/vue")['SfIconFacebook']
export const SfIconFavorite: typeof import("@storefront-ui/vue")['SfIconFavorite']
export const SfIconFavoriteFilled: typeof import("@storefront-ui/vue")['SfIconFavoriteFilled']
export const SfIconGridView: typeof import("@storefront-ui/vue")['SfIconGridView']
export const SfIconHelp: typeof import("@storefront-ui/vue")['SfIconHelp']
export const SfIconHome: typeof import("@storefront-ui/vue")['SfIconHome']
export const SfIconIndeterminateCheckBox: typeof import("@storefront-ui/vue")['SfIconIndeterminateCheckBox']
export const SfIconInfo: typeof import("@storefront-ui/vue")['SfIconInfo']
export const SfIconInstagram: typeof import("@storefront-ui/vue")['SfIconInstagram']
export const SfIconLanguage: typeof import("@storefront-ui/vue")['SfIconLanguage']
export const SfIconLocalShipping: typeof import("@storefront-ui/vue")['SfIconLocalShipping']
export const SfIconLocalFireDepartment: typeof import("@storefront-ui/vue")['SfIconLocal_fire_department']
export const SfIconLocationOn: typeof import("@storefront-ui/vue")['SfIconLocationOn']
export const SfIconLocationOnFilled: typeof import("@storefront-ui/vue")['SfIconLocationOnFilled']
export const SfIconLock: typeof import("@storefront-ui/vue")['SfIconLock']
export const SfIconLockOpen: typeof import("@storefront-ui/vue")['SfIconLockOpen']
export const SfIconLogin: typeof import("@storefront-ui/vue")['SfIconLogin']
export const SfIconLogout: typeof import("@storefront-ui/vue")['SfIconLogout']
export const SfIconMenu: typeof import("@storefront-ui/vue")['SfIconMenu']
export const SfIconMoreHoriz: typeof import("@storefront-ui/vue")['SfIconMoreHoriz']
export const SfIconMoreVert: typeof import("@storefront-ui/vue")['SfIconMoreVert']
export const SfIconOpenInNew: typeof import("@storefront-ui/vue")['SfIconOpenInNew']
export const SfIconOpenSource: typeof import("@storefront-ui/vue")['SfIconOpenSource']
export const SfIconPackage: typeof import("@storefront-ui/vue")['SfIconPackage']
export const SfIconPercent: typeof import("@storefront-ui/vue")['SfIconPercent']
export const SfIconPerson: typeof import("@storefront-ui/vue")['SfIconPerson']
export const SfIconPinterest: typeof import("@storefront-ui/vue")['SfIconPinterest']
export const SfIconPublishedWithChanges: typeof import("@storefront-ui/vue")['SfIconPublishedWithChanges']
export const SfIconRadioButtonChecked: typeof import("@storefront-ui/vue")['SfIconRadioButtonChecked']
export const SfIconRadioButtonUnchecked: typeof import("@storefront-ui/vue")['SfIconRadioButtonUnchecked']
export const SfIconReact: typeof import("@storefront-ui/vue")['SfIconReact']
export const SfIconRemove: typeof import("@storefront-ui/vue")['SfIconRemove']
export const SfIconRemoveShoppingCart: typeof import("@storefront-ui/vue")['SfIconRemoveShoppingCart']
export const SfIconSafetyCheck: typeof import("@storefront-ui/vue")['SfIconSafetyCheck']
export const SfIconSchedule: typeof import("@storefront-ui/vue")['SfIconSchedule']
export const SfIconSearch: typeof import("@storefront-ui/vue")['SfIconSearch']
export const SfIconSell: typeof import("@storefront-ui/vue")['SfIconSell']
export const SfIconShare: typeof import("@storefront-ui/vue")['SfIconShare']
export const SfIconShoppingCart: typeof import("@storefront-ui/vue")['SfIconShoppingCart']
export const SfIconShoppingCartCheckout: typeof import("@storefront-ui/vue")['SfIconShoppingCartCheckout']
export const SfIconSort: typeof import("@storefront-ui/vue")['SfIconSort']
export const SfIconStar: typeof import("@storefront-ui/vue")['SfIconStar']
export const SfIconStarFilled: typeof import("@storefront-ui/vue")['SfIconStarFilled']
export const SfIconStarHalf: typeof import("@storefront-ui/vue")['SfIconStarHalf']
export const SfIconThumbDown: typeof import("@storefront-ui/vue")['SfIconThumbDown']
export const SfIconThumbUp: typeof import("@storefront-ui/vue")['SfIconThumbUp']
export const SfIconTune: typeof import("@storefront-ui/vue")['SfIconTune']
export const SfIconTwitter: typeof import("@storefront-ui/vue")['SfIconTwitter']
export const SfIconUndo: typeof import("@storefront-ui/vue")['SfIconUndo']
export const SfIconUnfoldMore: typeof import("@storefront-ui/vue")['SfIconUnfoldMore']
export const SfIconUpload: typeof import("@storefront-ui/vue")['SfIconUpload']
export const SfIconViewList: typeof import("@storefront-ui/vue")['SfIconViewList']
export const SfIconVisibility: typeof import("@storefront-ui/vue")['SfIconVisibility']
export const SfIconVisibilityOff: typeof import("@storefront-ui/vue")['SfIconVisibilityOff']
export const SfIconVsfDiamond: typeof import("@storefront-ui/vue")['SfIconVsfDiamond']
export const SfIconVuejs: typeof import("@storefront-ui/vue")['SfIconVuejs']
export const SfIconVuestorefront: typeof import("@storefront-ui/vue")['SfIconVuestorefront']
export const SfIconWarehouse: typeof import("@storefront-ui/vue")['SfIconWarehouse']
export const SfIconWarning: typeof import("@storefront-ui/vue")['SfIconWarning']
export const SfIconYoutube: typeof import("@storefront-ui/vue")['SfIconYoutube']
export const SfInput: typeof import("@storefront-ui/vue")['SfInput']
export const SfLink: typeof import("@storefront-ui/vue")['SfLink']
export const SfListItem: typeof import("@storefront-ui/vue")['SfListItem']
export const SfLoaderCircular: typeof import("@storefront-ui/vue")['SfLoaderCircular']
export const SfLoaderLinear: typeof import("@storefront-ui/vue")['SfLoaderLinear']
export const SfModal: typeof import("@storefront-ui/vue")['SfModal']
export const SfProgressCircular: typeof import("@storefront-ui/vue")['SfProgressCircular']
export const SfProgressLinear: typeof import("@storefront-ui/vue")['SfProgressLinear']
export const SfRadio: typeof import("@storefront-ui/vue")['SfRadio']
export const SfRating: typeof import("@storefront-ui/vue")['SfRating']
export const SfRatingButton: typeof import("@storefront-ui/vue")['SfRatingButton']
export const SfScrollable: typeof import("@storefront-ui/vue")['SfScrollable']
export const SfSelect: typeof import("@storefront-ui/vue")['SfSelect']
export const SfSwitch: typeof import("@storefront-ui/vue")['SfSwitch']
export const SfTextarea: typeof import("@storefront-ui/vue")['SfTextarea']
export const SfThumbnail: typeof import("@storefront-ui/vue")['SfThumbnail']
export const SfTooltip: typeof import("@storefront-ui/vue")['SfTooltip']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyFooterNav: LazyComponent<typeof import("../app/components/FooterNav.vue")['default']>
export const LazyCatalogProductAddAttributeSet: LazyComponent<typeof import("../app/components/catalog/product/add-attribute-set.vue")['default']>
export const LazyCatalogProductAddAttribute: LazyComponent<typeof import("../app/components/catalog/product/add-attribute.vue")['default']>
export const LazyCatalogProductAddProduct: LazyComponent<typeof import("../app/components/catalog/product/add-product.vue")['default']>
export const LazyCatalogProductAddShowcase: LazyComponent<typeof import("../app/components/catalog/product/add-showcase.vue")['default']>
export const LazyCatalogProductAddStation: LazyComponent<typeof import("../app/components/catalog/product/add-station.vue")['default']>
export const LazyCatalogProductBestsellers: LazyComponent<typeof import("../app/components/catalog/product/bestsellers.vue")['default']>
export const LazyCatalogProductBrands: LazyComponent<typeof import("../app/components/catalog/product/brands.vue")['default']>
export const LazyCatalogProductColorOptions: LazyComponent<typeof import("../app/components/catalog/product/colorOptions.vue")['default']>
export const LazyCatalogProductDeals: LazyComponent<typeof import("../app/components/catalog/product/deals.vue")['default']>
export const LazyCatalogProductExclusives: LazyComponent<typeof import("../app/components/catalog/product/exclusives.vue")['default']>
export const LazyCatalogProductFeaturedproducts: LazyComponent<typeof import("../app/components/catalog/product/featuredproducts.vue")['default']>
export const LazyCatalogProductGiftCard: LazyComponent<typeof import("../app/components/catalog/product/giftCard.vue")['default']>
export const LazyCatalogProductLatestproducts: LazyComponent<typeof import("../app/components/catalog/product/latestproducts.vue")['default']>
export const LazyCatalogProductCard: LazyComponent<typeof import("../app/components/catalog/product/productCard.vue")['default']>
export const LazyCatalogProductCompare: LazyComponent<typeof import("../app/components/catalog/product/productCompare.vue")['default']>
export const LazyCatalogProductCompareTable: LazyComponent<typeof import("../app/components/catalog/product/productCompareTable.vue")['default']>
export const LazyCatalogProductDetails: LazyComponent<typeof import("../app/components/catalog/product/productDetails.vue")['default']>
export const LazyCatalogProductFaqs: LazyComponent<typeof import("../app/components/catalog/product/productFaqs.vue")['default']>
export const LazyCatalogProductGallery: LazyComponent<typeof import("../app/components/catalog/product/productGallery.vue")['default']>
export const LazyCatalogProductQty: LazyComponent<typeof import("../app/components/catalog/product/productQty.vue")['default']>
export const LazyCatalogProductReviews: LazyComponent<typeof import("../app/components/catalog/product/productReviews.vue")['default']>
export const LazyCatalogProductSpecs: LazyComponent<typeof import("../app/components/catalog/product/productSpecs.vue")['default']>
export const LazyCatalogProductRadiostation: LazyComponent<typeof import("../app/components/catalog/product/radiostation.vue")['default']>
export const LazyCatalogProductRecentlyviewed: LazyComponent<typeof import("../app/components/catalog/product/recentlyviewed.vue")['default']>
export const LazyCatalogProductRelatedproducts: LazyComponent<typeof import("../app/components/catalog/product/relatedproducts.vue")['default']>
export const LazyCatalogProductRelatedstations: LazyComponent<typeof import("../app/components/catalog/product/relatedstations.vue")['default']>
export const LazyCatalogProductShippingOptions: LazyComponent<typeof import("../app/components/catalog/product/shippingOptions.vue")['default']>
export const LazyCatalogProductSizeOptions: LazyComponent<typeof import("../app/components/catalog/product/sizeOptions.vue")['default']>
export const LazyCatalogProductUpdateAttributeSet: LazyComponent<typeof import("../app/components/catalog/product/update-attribute-set.vue")['default']>
export const LazyCatalogProductUpdateAttribute: LazyComponent<typeof import("../app/components/catalog/product/update-attribute.vue")['default']>
export const LazyCatalogProductUpdateProduct: LazyComponent<typeof import("../app/components/catalog/product/update-product.vue")['default']>
export const LazyCatalogProductUpdateShowcase: LazyComponent<typeof import("../app/components/catalog/product/update-showcase.vue")['default']>
export const LazyCatalogShopsRelatedstores: LazyComponent<typeof import("../app/components/catalog/shops/relatedstores.vue")['default']>
export const LazyCatalogShopsRestaurant: LazyComponent<typeof import("../app/components/catalog/shops/restaurant.vue")['default']>
export const LazyCatalogShopsStores: LazyComponent<typeof import("../app/components/catalog/shops/stores.vue")['default']>
export const LazyCatalogVendorBlocksBiggestcustomers: LazyComponent<typeof import("../app/components/catalog/vendor/blocks/biggestcustomers.vue")['default']>
export const LazyCatalogVendorBlocksLowestselling: LazyComponent<typeof import("../app/components/catalog/vendor/blocks/lowestselling.vue")['default']>
export const LazyCatalogVendorBlocksTopcategories: LazyComponent<typeof import("../app/components/catalog/vendor/blocks/topcategories.vue")['default']>
export const LazyCatalogVendorBlocksTopproducts: LazyComponent<typeof import("../app/components/catalog/vendor/blocks/topproducts.vue")['default']>
export const LazyCatalogVendorPagesAttributes: LazyComponent<typeof import("../app/components/catalog/vendor/pages/attributes.vue")['default']>
export const LazyCatalogVendorPagesCommissions: LazyComponent<typeof import("../app/components/catalog/vendor/pages/commissions.vue")['default']>
export const LazyCatalogVendorPagesCrm: LazyComponent<typeof import("../app/components/catalog/vendor/pages/crm.vue")['default']>
export const LazyCatalogVendorPagesDashboard: LazyComponent<typeof import("../app/components/catalog/vendor/pages/dashboard.vue")['default']>
export const LazyCatalogVendorPagesEmails: LazyComponent<typeof import("../app/components/catalog/vendor/pages/emails.vue")['default']>
export const LazyCatalogVendorPagesEnquiries: LazyComponent<typeof import("../app/components/catalog/vendor/pages/enquiries.vue")['default']>
export const LazyCatalogVendorPagesInvoices: LazyComponent<typeof import("../app/components/catalog/vendor/pages/invoices.vue")['default']>
export const LazyCatalogVendorPagesOrders: LazyComponent<typeof import("../app/components/catalog/vendor/pages/orders.vue")['default']>
export const LazyCatalogVendorPagesProducts: LazyComponent<typeof import("../app/components/catalog/vendor/pages/products.vue")['default']>
export const LazyCatalogVendorPagesReviews: LazyComponent<typeof import("../app/components/catalog/vendor/pages/reviews.vue")['default']>
export const LazyCatalogVendorPagesShipments: LazyComponent<typeof import("../app/components/catalog/vendor/pages/shipments.vue")['default']>
export const LazyCatalogVendorPagesStores: LazyComponent<typeof import("../app/components/catalog/vendor/pages/stores.vue")['default']>
export const LazyContentBlocksBreadcrumbs: LazyComponent<typeof import("../app/components/content/blocks/breadcrumbs.vue")['default']>
export const LazyContentBlocksCurrencySwitcher: LazyComponent<typeof import("../app/components/content/blocks/currencySwitcher.vue")['default']>
export const LazyContentBlocksLanguageSwitcher: LazyComponent<typeof import("../app/components/content/blocks/languageSwitcher.vue")['default']>
export const LazyContentBlocksVideoproduct: LazyComponent<typeof import("../app/components/content/blocks/videoproduct.vue")['default']>
export const LazyEcosystemmenu: LazyComponent<typeof import("../app/components/ecosystemmenu.vue")['default']>
export const LazyMarketingAddCoupon: LazyComponent<typeof import("../app/components/marketing/add-coupon.vue")['default']>
export const LazyMarketingAddRewards: LazyComponent<typeof import("../app/components/marketing/add-rewards.vue")['default']>
export const LazyMarketingCoupons: LazyComponent<typeof import("../app/components/marketing/coupons.vue")['default']>
export const LazyMarketingPromotionsCoupons: LazyComponent<typeof import("../app/components/marketing/promotions/coupons.vue")['default']>
export const LazyMarketingPromotionsGiftcard[id]: LazyComponent<typeof import("../app/components/marketing/promotions/giftcard/[id].vue")['default']>
export const LazyMarketingPromotionsGiftcardReload: LazyComponent<typeof import("../app/components/marketing/promotions/giftcard/reload.vue")['default']>
export const LazyMarketingPromotionsGiftcards: LazyComponent<typeof import("../app/components/marketing/promotions/giftcards.vue")['default']>
export const LazyMarketingPromotionsSubscription[id]: LazyComponent<typeof import("../app/components/marketing/promotions/subscription/[id].vue")['default']>
export const LazyMarketingPromotionsSubscriptions: LazyComponent<typeof import("../app/components/marketing/promotions/subscriptions.vue")['default']>
export const LazyMarketingUpdateRewards: LazyComponent<typeof import("../app/components/marketing/update-rewards.vue")['default']>
export const LazyMenusLowernav: LazyComponent<typeof import("../app/components/menus/lowernav.vue")['default']>
export const LazyPartialsLocaleSelector: LazyComponent<typeof import("../app/components/partials/LocaleSelector.vue")['default']>
export const LazyPartialsStripePayment: LazyComponent<typeof import("../app/components/partials/StripePayment.vue")['default']>
export const LazyPartialsAddToCartBtn: LazyComponent<typeof import("../app/components/partials/addToCartBtn.vue")['default']>
export const LazyPartialsCartItem: LazyComponent<typeof import("../app/components/partials/cartItem.vue")['default']>
export const LazyPartialsCheckoutButton: LazyComponent<typeof import("../app/components/partials/checkoutButton.vue")['default']>
export const LazyPartialsCompareBtn: LazyComponent<typeof import("../app/components/partials/compareBtn.vue")['default']>
export const LazyPartialsRatings: LazyComponent<typeof import("../app/components/partials/ratings.vue")['default']>
export const LazyPartialsStoreCurrencySelector: LazyComponent<typeof import("../app/components/partials/store/CurrencySelector.vue")['default']>
export const LazyPartialsStoreSwitcher: LazyComponent<typeof import("../app/components/partials/store/StoreSwitcher.vue")['default']>
export const LazyRelatedRelatedposts: LazyComponent<typeof import("../app/components/related/relatedposts.vue")['default']>
export const LazyRelatedRelatedproducts: LazyComponent<typeof import("../app/components/related/relatedproducts.vue")['default']>
export const LazySalesOrderDetailsDialog: LazyComponent<typeof import("../app/components/sales/OrderDetailsDialog.vue")['default']>
export const LazySalesOrderManagement: LazyComponent<typeof import("../app/components/sales/OrderManagement.vue")['default']>
export const LazySalesReceiptsTab: LazyComponent<typeof import("../app/components/sales/ReceiptsTab.vue")['default']>
export const LazySalesReturnRequestDialog: LazyComponent<typeof import("../app/components/sales/ReturnRequestDialog.vue")['default']>
export const LazySalesReturnsTab: LazyComponent<typeof import("../app/components/sales/ReturnsTab.vue")['default']>
export const LazySalesTransactionsTab: LazyComponent<typeof import("../app/components/sales/TransactionsTab.vue")['default']>
export const LazySalesBrandsRelatedbrands: LazyComponent<typeof import("../app/components/sales/brands/relatedbrands.vue")['default']>
export const LazySalesCreditMemos: LazyComponent<typeof import("../app/components/sales/creditMemos.vue")['default']>
export const LazySalesInvoices: LazyComponent<typeof import("../app/components/sales/invoices.vue")['default']>
export const LazySalesOrdersAgreements: LazyComponent<typeof import("../app/components/sales/orders/agreements.vue")['default']>
export const LazySalesOrdersCreditmemo[id]: LazyComponent<typeof import("../app/components/sales/orders/creditmemo/[id].vue")['default']>
export const LazySalesOrdersCreditmemos: LazyComponent<typeof import("../app/components/sales/orders/creditmemos.vue")['default']>
export const LazySalesOrdersInvoice[id]: LazyComponent<typeof import("../app/components/sales/orders/invoice/[id].vue")['default']>
export const LazySalesOrdersInvoices: LazyComponent<typeof import("../app/components/sales/orders/invoices.vue")['default']>
export const LazySalesOrdersMyOrder[id]: LazyComponent<typeof import("../app/components/sales/orders/my-order/[id].vue")['default']>
export const LazySalesOrdersMyOrders: LazyComponent<typeof import("../app/components/sales/orders/my-orders.vue")['default']>
export const LazySalesOrdersPayments: LazyComponent<typeof import("../app/components/sales/orders/payments.vue")['default']>
export const LazySalesOrdersReturn: LazyComponent<typeof import("../app/components/sales/orders/return.vue")['default']>
export const LazySalesOrdersReturns: LazyComponent<typeof import("../app/components/sales/orders/returns.vue")['default']>
export const LazySalesOrdersShipment[id]: LazyComponent<typeof import("../app/components/sales/orders/shipment/[id].vue")['default']>
export const LazySalesOrdersShipments: LazyComponent<typeof import("../app/components/sales/orders/shipments.vue")['default']>
export const LazySalesOrdersTransaction[id]: LazyComponent<typeof import("../app/components/sales/orders/transaction/[id].vue")['default']>
export const LazySalesOrdersTransactions: LazyComponent<typeof import("../app/components/sales/orders/transactions.vue")['default']>
export const LazySalesOrdersTab: LazyComponent<typeof import("../app/components/sales/ordersTab.vue")['default']>
export const LazySalesPaymentsPriceDisplay: LazyComponent<typeof import("../app/components/sales/payments/PriceDisplay.vue")['default']>
export const LazySalesPaymentsStripePaymentElement: LazyComponent<typeof import("../app/components/sales/payments/StripePaymentElement.vue")['default']>
export const LazySearch: LazyComponent<typeof import("../app/components/search/search.vue")['default']>
export const LazyShopCartItem: LazyComponent<typeof import("../app/components/shop/cart/cartItem.vue")['default']>
export const LazyShopCartCheckout: LazyComponent<typeof import("../app/components/shop/cart/checkout.vue")['default']>
export const LazyShopCheckoutStripeCardElement: LazyComponent<typeof import("../app/components/shop/checkout/StripeCardElement.vue")['default']>
export const LazyShopCheckoutStripeCheckout: LazyComponent<typeof import("../app/components/shop/checkout/StripeCheckout.vue")['default']>
export const LazyShopCheckoutAddressBilling: LazyComponent<typeof import("../app/components/shop/checkout/addressBilling.vue")['default']>
export const LazyShopCheckoutAddressShipping: LazyComponent<typeof import("../app/components/shop/checkout/addressShipping.vue")['default']>
export const LazyShopCheckoutCartProductItem: LazyComponent<typeof import("../app/components/shop/checkout/cart/ProductItem.vue")['default']>
export const LazyShopCheckoutCartPromotionItem: LazyComponent<typeof import("../app/components/shop/checkout/cart/PromotionItem.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
export const LazySfAccordionItem: LazyComponent<typeof import("@storefront-ui/vue")['SfAccordionItem']>
export const LazySfBadge: LazyComponent<typeof import("@storefront-ui/vue")['SfBadge']>
export const LazySfButton: LazyComponent<typeof import("@storefront-ui/vue")['SfButton']>
export const LazySfCheckbox: LazyComponent<typeof import("@storefront-ui/vue")['SfCheckbox']>
export const LazySfChip: LazyComponent<typeof import("@storefront-ui/vue")['SfChip']>
export const LazySfCounter: LazyComponent<typeof import("@storefront-ui/vue")['SfCounter']>
export const LazySfDrawer: LazyComponent<typeof import("@storefront-ui/vue")['SfDrawer']>
export const LazySfDropdown: LazyComponent<typeof import("@storefront-ui/vue")['SfDropdown']>
export const LazySfIconAdd: LazyComponent<typeof import("@storefront-ui/vue")['SfIconAdd']>
export const LazySfIconAddShoppingCart: LazyComponent<typeof import("@storefront-ui/vue")['SfIconAddShoppingCart']>
export const LazySfIconAlokai: LazyComponent<typeof import("@storefront-ui/vue")['SfIconAlokai']>
export const LazySfIconAlokaiFull: LazyComponent<typeof import("@storefront-ui/vue")['SfIconAlokaiFull']>
export const LazySfIconArrowBack: LazyComponent<typeof import("@storefront-ui/vue")['SfIconArrowBack']>
export const LazySfIconArrowDownward: LazyComponent<typeof import("@storefront-ui/vue")['SfIconArrowDownward']>
export const LazySfIconArrowForward: LazyComponent<typeof import("@storefront-ui/vue")['SfIconArrowForward']>
export const LazySfIconArrowUpward: LazyComponent<typeof import("@storefront-ui/vue")['SfIconArrowUpward']>
export const LazySfIconBase: LazyComponent<typeof import("@storefront-ui/vue")['SfIconBase']>
export const LazySfIconBlock: LazyComponent<typeof import("@storefront-ui/vue")['SfIconBlock']>
export const LazySfIconCalendarToday: LazyComponent<typeof import("@storefront-ui/vue")['SfIconCalendarToday']>
export const LazySfIconCall: LazyComponent<typeof import("@storefront-ui/vue")['SfIconCall']>
export const LazySfIconCancel: LazyComponent<typeof import("@storefront-ui/vue")['SfIconCancel']>
export const LazySfIconCheck: LazyComponent<typeof import("@storefront-ui/vue")['SfIconCheck']>
export const LazySfIconCheckBox: LazyComponent<typeof import("@storefront-ui/vue")['SfIconCheckBox']>
export const LazySfIconCheckBoxOutlineBlank: LazyComponent<typeof import("@storefront-ui/vue")['SfIconCheckBoxOutlineBlank']>
export const LazySfIconCheckCircle: LazyComponent<typeof import("@storefront-ui/vue")['SfIconCheckCircle']>
export const LazySfIconChevronLeft: LazyComponent<typeof import("@storefront-ui/vue")['SfIconChevronLeft']>
export const LazySfIconChevronRight: LazyComponent<typeof import("@storefront-ui/vue")['SfIconChevronRight']>
export const LazySfIconCircle: LazyComponent<typeof import("@storefront-ui/vue")['SfIconCircle']>
export const LazySfIconClose: LazyComponent<typeof import("@storefront-ui/vue")['SfIconClose']>
export const LazySfIconCloseSm: LazyComponent<typeof import("@storefront-ui/vue")['SfIconCloseSm']>
export const LazySfIconCompareArrows: LazyComponent<typeof import("@storefront-ui/vue")['SfIconCompareArrows']>
export const LazySfIconContactSupport: LazyComponent<typeof import("@storefront-ui/vue")['SfIconContactSupport']>
export const LazySfIconCreditCard: LazyComponent<typeof import("@storefront-ui/vue")['SfIconCreditCard']>
export const LazySfIconDelete: LazyComponent<typeof import("@storefront-ui/vue")['SfIconDelete']>
export const LazySfIconDownload: LazyComponent<typeof import("@storefront-ui/vue")['SfIconDownload']>
export const LazySfIconEmail: LazyComponent<typeof import("@storefront-ui/vue")['SfIconEmail']>
export const LazySfIconError: LazyComponent<typeof import("@storefront-ui/vue")['SfIconError']>
export const LazySfIconExpandLess: LazyComponent<typeof import("@storefront-ui/vue")['SfIconExpandLess']>
export const LazySfIconExpandMore: LazyComponent<typeof import("@storefront-ui/vue")['SfIconExpandMore']>
export const LazySfIconFacebook: LazyComponent<typeof import("@storefront-ui/vue")['SfIconFacebook']>
export const LazySfIconFavorite: LazyComponent<typeof import("@storefront-ui/vue")['SfIconFavorite']>
export const LazySfIconFavoriteFilled: LazyComponent<typeof import("@storefront-ui/vue")['SfIconFavoriteFilled']>
export const LazySfIconGridView: LazyComponent<typeof import("@storefront-ui/vue")['SfIconGridView']>
export const LazySfIconHelp: LazyComponent<typeof import("@storefront-ui/vue")['SfIconHelp']>
export const LazySfIconHome: LazyComponent<typeof import("@storefront-ui/vue")['SfIconHome']>
export const LazySfIconIndeterminateCheckBox: LazyComponent<typeof import("@storefront-ui/vue")['SfIconIndeterminateCheckBox']>
export const LazySfIconInfo: LazyComponent<typeof import("@storefront-ui/vue")['SfIconInfo']>
export const LazySfIconInstagram: LazyComponent<typeof import("@storefront-ui/vue")['SfIconInstagram']>
export const LazySfIconLanguage: LazyComponent<typeof import("@storefront-ui/vue")['SfIconLanguage']>
export const LazySfIconLocalShipping: LazyComponent<typeof import("@storefront-ui/vue")['SfIconLocalShipping']>
export const LazySfIconLocalFireDepartment: LazyComponent<typeof import("@storefront-ui/vue")['SfIconLocal_fire_department']>
export const LazySfIconLocationOn: LazyComponent<typeof import("@storefront-ui/vue")['SfIconLocationOn']>
export const LazySfIconLocationOnFilled: LazyComponent<typeof import("@storefront-ui/vue")['SfIconLocationOnFilled']>
export const LazySfIconLock: LazyComponent<typeof import("@storefront-ui/vue")['SfIconLock']>
export const LazySfIconLockOpen: LazyComponent<typeof import("@storefront-ui/vue")['SfIconLockOpen']>
export const LazySfIconLogin: LazyComponent<typeof import("@storefront-ui/vue")['SfIconLogin']>
export const LazySfIconLogout: LazyComponent<typeof import("@storefront-ui/vue")['SfIconLogout']>
export const LazySfIconMenu: LazyComponent<typeof import("@storefront-ui/vue")['SfIconMenu']>
export const LazySfIconMoreHoriz: LazyComponent<typeof import("@storefront-ui/vue")['SfIconMoreHoriz']>
export const LazySfIconMoreVert: LazyComponent<typeof import("@storefront-ui/vue")['SfIconMoreVert']>
export const LazySfIconOpenInNew: LazyComponent<typeof import("@storefront-ui/vue")['SfIconOpenInNew']>
export const LazySfIconOpenSource: LazyComponent<typeof import("@storefront-ui/vue")['SfIconOpenSource']>
export const LazySfIconPackage: LazyComponent<typeof import("@storefront-ui/vue")['SfIconPackage']>
export const LazySfIconPercent: LazyComponent<typeof import("@storefront-ui/vue")['SfIconPercent']>
export const LazySfIconPerson: LazyComponent<typeof import("@storefront-ui/vue")['SfIconPerson']>
export const LazySfIconPinterest: LazyComponent<typeof import("@storefront-ui/vue")['SfIconPinterest']>
export const LazySfIconPublishedWithChanges: LazyComponent<typeof import("@storefront-ui/vue")['SfIconPublishedWithChanges']>
export const LazySfIconRadioButtonChecked: LazyComponent<typeof import("@storefront-ui/vue")['SfIconRadioButtonChecked']>
export const LazySfIconRadioButtonUnchecked: LazyComponent<typeof import("@storefront-ui/vue")['SfIconRadioButtonUnchecked']>
export const LazySfIconReact: LazyComponent<typeof import("@storefront-ui/vue")['SfIconReact']>
export const LazySfIconRemove: LazyComponent<typeof import("@storefront-ui/vue")['SfIconRemove']>
export const LazySfIconRemoveShoppingCart: LazyComponent<typeof import("@storefront-ui/vue")['SfIconRemoveShoppingCart']>
export const LazySfIconSafetyCheck: LazyComponent<typeof import("@storefront-ui/vue")['SfIconSafetyCheck']>
export const LazySfIconSchedule: LazyComponent<typeof import("@storefront-ui/vue")['SfIconSchedule']>
export const LazySfIconSearch: LazyComponent<typeof import("@storefront-ui/vue")['SfIconSearch']>
export const LazySfIconSell: LazyComponent<typeof import("@storefront-ui/vue")['SfIconSell']>
export const LazySfIconShare: LazyComponent<typeof import("@storefront-ui/vue")['SfIconShare']>
export const LazySfIconShoppingCart: LazyComponent<typeof import("@storefront-ui/vue")['SfIconShoppingCart']>
export const LazySfIconShoppingCartCheckout: LazyComponent<typeof import("@storefront-ui/vue")['SfIconShoppingCartCheckout']>
export const LazySfIconSort: LazyComponent<typeof import("@storefront-ui/vue")['SfIconSort']>
export const LazySfIconStar: LazyComponent<typeof import("@storefront-ui/vue")['SfIconStar']>
export const LazySfIconStarFilled: LazyComponent<typeof import("@storefront-ui/vue")['SfIconStarFilled']>
export const LazySfIconStarHalf: LazyComponent<typeof import("@storefront-ui/vue")['SfIconStarHalf']>
export const LazySfIconThumbDown: LazyComponent<typeof import("@storefront-ui/vue")['SfIconThumbDown']>
export const LazySfIconThumbUp: LazyComponent<typeof import("@storefront-ui/vue")['SfIconThumbUp']>
export const LazySfIconTune: LazyComponent<typeof import("@storefront-ui/vue")['SfIconTune']>
export const LazySfIconTwitter: LazyComponent<typeof import("@storefront-ui/vue")['SfIconTwitter']>
export const LazySfIconUndo: LazyComponent<typeof import("@storefront-ui/vue")['SfIconUndo']>
export const LazySfIconUnfoldMore: LazyComponent<typeof import("@storefront-ui/vue")['SfIconUnfoldMore']>
export const LazySfIconUpload: LazyComponent<typeof import("@storefront-ui/vue")['SfIconUpload']>
export const LazySfIconViewList: LazyComponent<typeof import("@storefront-ui/vue")['SfIconViewList']>
export const LazySfIconVisibility: LazyComponent<typeof import("@storefront-ui/vue")['SfIconVisibility']>
export const LazySfIconVisibilityOff: LazyComponent<typeof import("@storefront-ui/vue")['SfIconVisibilityOff']>
export const LazySfIconVsfDiamond: LazyComponent<typeof import("@storefront-ui/vue")['SfIconVsfDiamond']>
export const LazySfIconVuejs: LazyComponent<typeof import("@storefront-ui/vue")['SfIconVuejs']>
export const LazySfIconVuestorefront: LazyComponent<typeof import("@storefront-ui/vue")['SfIconVuestorefront']>
export const LazySfIconWarehouse: LazyComponent<typeof import("@storefront-ui/vue")['SfIconWarehouse']>
export const LazySfIconWarning: LazyComponent<typeof import("@storefront-ui/vue")['SfIconWarning']>
export const LazySfIconYoutube: LazyComponent<typeof import("@storefront-ui/vue")['SfIconYoutube']>
export const LazySfInput: LazyComponent<typeof import("@storefront-ui/vue")['SfInput']>
export const LazySfLink: LazyComponent<typeof import("@storefront-ui/vue")['SfLink']>
export const LazySfListItem: LazyComponent<typeof import("@storefront-ui/vue")['SfListItem']>
export const LazySfLoaderCircular: LazyComponent<typeof import("@storefront-ui/vue")['SfLoaderCircular']>
export const LazySfLoaderLinear: LazyComponent<typeof import("@storefront-ui/vue")['SfLoaderLinear']>
export const LazySfModal: LazyComponent<typeof import("@storefront-ui/vue")['SfModal']>
export const LazySfProgressCircular: LazyComponent<typeof import("@storefront-ui/vue")['SfProgressCircular']>
export const LazySfProgressLinear: LazyComponent<typeof import("@storefront-ui/vue")['SfProgressLinear']>
export const LazySfRadio: LazyComponent<typeof import("@storefront-ui/vue")['SfRadio']>
export const LazySfRating: LazyComponent<typeof import("@storefront-ui/vue")['SfRating']>
export const LazySfRatingButton: LazyComponent<typeof import("@storefront-ui/vue")['SfRatingButton']>
export const LazySfScrollable: LazyComponent<typeof import("@storefront-ui/vue")['SfScrollable']>
export const LazySfSelect: LazyComponent<typeof import("@storefront-ui/vue")['SfSelect']>
export const LazySfSwitch: LazyComponent<typeof import("@storefront-ui/vue")['SfSwitch']>
export const LazySfTextarea: LazyComponent<typeof import("@storefront-ui/vue")['SfTextarea']>
export const LazySfThumbnail: LazyComponent<typeof import("@storefront-ui/vue")['SfThumbnail']>
export const LazySfTooltip: LazyComponent<typeof import("@storefront-ui/vue")['SfTooltip']>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
